[package]
name = "lightbi-export"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust_xlsxwriter = "0.80.0"
lightbi-view = { path = "../lightbi-view" }
lightbi-insight = { path = "../lightbi-insight" }
lightbi-runtime-backend = { path = "../lightbi-runtime-backend" }
