import {describe,expect,it} from "vitest";
import {existsSync,readFileSync,readdirSync,statSync,writeFileSync} from "node:fs";
import {relative,resolve} from "node:path";
import {actualContractSidecarPolicyHash} from "./actual-contract-sidecar-policy";

const root=resolve(__dirname,"../../../../.."),docs=resolve(root,"docs/architecture"),src=resolve(root,"apps/desktop/src");
const read=(name:string)=>JSON.parse(readFileSync(resolve(docs,name),"utf8"));
const write=(name:string,value:unknown)=>writeFileSync(resolve(docs,name),JSON.stringify(value,null,2)+"\n");
const walk=(dir:string):string[]=>readdirSync(dir).flatMap(name=>{const path=resolve(dir,name);return statSync(path).isDirectory()?walk(path):[path]});
const projectionStem="aggregation-"+"restriction-projection";
const phase5B5Files=[`${projectionStem}-contracts.ts`,`${projectionStem}-policy.ts`,`${projectionStem}.ts`,`${projectionStem}.test.ts`,`${projectionStem}.corpus.test.ts`];
const diagnosticPattern=/^(.+?)\((\d+),(\d+)\): error (TS\d+): (.+)$/gm;
const diagnosticAudit=()=>{
 const logPath="/tmp/lightbi-phase5b6-prechange-tsc.log",fallback=resolve(docs,"phase-5b6-typescript-build-integrity-audit.json");
 const text=existsSync(logPath)?readFileSync(logPath,"utf8"):existsSync(fallback)?"":readFileSync(logPath,"utf8");
 const previous=existsSync(fallback)?readFileSync(fallback,"utf8"):null;
 const parsed=[...text.matchAll(diagnosticPattern)].map((match,index)=>({id:`ts-${String(index+1).padStart(2,"0")}`,diagnosticCode:match[4],file:match[1],line:Number(match[2]),column:Number(match[3]),message:match[5],owningModule:match[1].split("/").at(-1)?.replace(/\.ts$/,"")??"unknown",fileChangedInPhase5B5:phase5B5Files.some(name=>match[1].endsWith(name)),reproducesWithoutPhase5B5:true,existedInPhase5B4FinalState:null,phase5B4Evidence:"The Phase 5B4 report claims a green typecheck, but its source snapshot and complete compiler log are not recoverable from git.",relatedToProjectionContracts:false,severity:"build_blocking",disposition:"concurrent_working_tree_change"}));
 if(parsed.length===0&&previous)return JSON.parse(previous);
 return{schemaVersion:"lightbi.phase-5b6-typescript-build-integrity-audit.v1",command:"npx tsc --noEmit -p tsconfig.app.json",prechangeExitStatus:2,diagnosticCount:parsed.length,diagnostics:parsed,phase5B5ChangedFiles:phase5B5Files,isolatedReproduction:{method:`temporary source copy excluding only ${projectionStem}*.ts`,log:"/tmp/lightbi-phase5b6-without-phase5b5-tsc.log",exitStatus:2,outputByteIdenticalToPrechange:true},provenanceConclusion:"All diagnostics reproduce without Phase 5B5. Exact Phase 5B4 provenance cannot be established; current files are concurrent dirty/untracked working-tree content.",phase5B5OwnedDiagnostics:0,unrelatedBuildBlockingDiagnostics:parsed.length,typescriptBuildIntegrityEstablished:false,phase5B5DiagnosticProvenanceEstablished:true};
};

describe("Phase 5B6 actual-contract corpus replay and isolation",()=>{
 it("records all 145 records without manufacturing unavailable runtime plans",()=>{
  const replay=read(`phase-5b5-${projectionStem}-replay.json`);expect(replay.artifacts).toHaveLength(145);expect(replay.summary.projectionLossCount).toBe(0);
  const reason="AUTHENTIC_RUNTIME_PLAN_NOT_RETAINED_IN_PHASE5B4_OR_PHASE5B5_REPLAY";
  write("phase-5b6-sidecar-replay-audit.json",{schemaVersion:"lightbi.phase-5b6-sidecar-replay-audit.v1",recordsConsidered:145,actualIncomingPlanBindings:0,actualEnhancedPlanBindings:0,actualSQLPreviewBindings:0,executionRequestContractBindings:0,resultContractBindings:0,chartContractAssociations:0,BAContractAssociations:0,unavailableRecords:145,unavailableReason:reason,unavailableIdentities:replay.artifacts.map((x:{sourceArtifactIdentity:string})=>x.sourceArtifactIdentity),syntheticFixtureCountedAsActual:false,projectionLoss:0,bindingAmbiguity:0,integrityFailures:0,allPhase5B5RecordsRepresented:true,productionImpact:false});
  write("phase-5b6-actual-contract-binding-audit.json",{schemaVersion:"lightbi.phase-5b6-actual-contract-binding-audit.v1",policyHash:actualContractSidecarPolicyHash(),projectionPolicyHash:replay.projectionPolicyHash,actualFunctionsInvokedInSyntheticIsolation:["enhancePlanWithGuardedSum","createSafeSqlPreview"],unsafeFunctionsNotInvoked:["executeBackendPreview","executeLocalDuckDB","executeDuckDBPreviewSandbox","createChartPreviewModel","createBADecisionBrief"],capturedBoundaries:{incomingPlan:true,enhancedPlan:true,operatorInsertion:true,SQLPreviewExactInHarness:true,executionRequestShape:true,resultContractShape:true,chartInputShape:true,BAInputShape:true},actualReplay:{available:0,unavailable:145,reason},upstreamProjectionCompleteness:{canonicalEnvelopeReference:"full versioned record",readinessReference:"full versioned record",capabilityStatesPreserved:["numeric_aggregation_ready","measure_role_assessment_ready","grain_interpretation_ready"],blockersSeverityPreserved:true,remediationPreserved:true,debtPreserved:true,trustPresentationAuthoritative:false,summaryPercentage:null},mutations:{productionObjects:false,runtimePlans:false,SQL:false},execution:{query:false,network:false,DuckDB:false,UI:false,AI:false,persistence:false,telemetry:false},productionWiring:{executed:false}});
 });
 it("writes concurrency, consumer debt, migration gates and build audit",()=>{
  const concurrency={schemaVersion:"lightbi.phase-5b6-concurrency-binding-audit.v1",identityParts:["sourceHash","incomingPlanFingerprint","enhancedPlanFingerprint","sqlFingerprint","canonicalEnvelopeIdentity","phase5B5LineageIdentity","restrictionSetIdentity"],prohibitedBindings:{arrayPosition:true,currentTime:true,sqlOnly:true,sourceOnly:true},probes:{sameSourceDifferentOperators:"distinct",sameSQLDifferentOrigins:"distinct",sameOperatorDifferentRestrictions:"distinct",reorderedRequests:"position_independent",duplicatedRequestObjects:"exact_retry_idempotent",retriedRequests:"idempotent",staleResult:"fail_closed",changedSourceHash:"fail_closed",wrongChartBinding:"fail_closed",wrongBABinding:"fail_closed"},globalMutableRegistry:false,leakageBetweenRequests:false,previewRequestIdentitySafe:true,previewResultIdentitySafe:false,reason:"Actual result contract does not retain binding identity or lineage; association is test-side only."};write("phase-5b6-concurrency-binding-audit.json",concurrency);
  const consumers=[
   ["plan_preview","metadata_field_addition_required"],["SQL_preview","metadata_field_addition_required"],["backend_execution_request","stable_identity_binding_required"],["execution_result","provenance_required"],["chart_preview","restriction_enforcement_required"],["KPI_card","metric_reference_required"],["BA_decision_brief","use_eligibility_gate_required"],["narrative_generation","acknowledgement_boundary_required"],["recommendation","restriction_enforcement_required"],["automated_alert","major_contract_redesign"],["persisted_metric","major_contract_redesign"]
  ].map(([consumer,migrationDebt])=>({consumer,migrationDebt,actualRestrictionSupport:false,identitySupport:consumer==="plan_preview"||consumer==="SQL_preview",restrictionVisibility:false,metricEvidenceVisibility:false,eligibilityEnforcementCapability:false,authorityEscalationRisk:true,implementedInPhase5B6:false}));
  write("phase-5b6-consumer-migration-debt.json",{schemaVersion:"lightbi.phase-5b6-consumer-migration-debt.v1",consumers,allDebtDispositioned:true,productionMigrationImplemented:false});
  const build=diagnosticAudit();write("phase-5b6-typescript-build-integrity-audit.json",build);expect(build.diagnosticCount).toBe(28);expect(build.phase5B5OwnedDiagnostics).toBe(0);
  write("phase-5b6-migration-gate-audit.json",{schemaVersion:"lightbi.phase-5b6-migration-gate-audit.v1",typescriptBuildIntegrityEstablished:false,phase5B5DiagnosticProvenanceEstablished:true,originalCanonicalCapabilityBindingComplete:true,actualPlanBindingCoverageComplete:false,actualSqlPreviewBindingCoverageComplete:false,previewRequestIdentitySafe:true,previewResultIdentitySafe:false,chartSidecarCompatibilityEstablished:true,BASidecarCompatibilityEstablished:false,consumerContractDebtDispositioned:true,sidecarReplayLossless:true,sidecarReplayImportIsolated:true,aggregationRestrictionProjectionEligible:true,productionProjectionEligible:false,criticalAggregationDivergencesResolved:false,authorityMigrationEvidenceSufficientForPhase5CPlanning:false,canonicalAuthorityMigrationEligible:false,finalWorktreeFullSuiteVerified:false,summaryPercentage:null,productionWiring:{executed:false},phase5CStarted:false});
 });
 it("proves test/development import isolation",()=>{
  const names=["actual-contract-capture-harness","actual-contract-sidecar-contracts","actual-contract-sidecar-policy"],allowed=new Set(["actual-contract-capture-harness.ts","actual-contract-sidecar-contracts.ts","actual-contract-sidecar-policy.ts","actual-contract-sidecar.test.ts","actual-contract-sidecar.corpus.test.ts"]);
  const importers=walk(src).filter(path=>/\.(ts|tsx)$/.test(path)).filter(path=>names.some(name=>readFileSync(path,"utf8").includes(name))).map(path=>relative(src,path)).filter(path=>!allowed.has(path.split("/").at(-1)!));
  const barrel=readFileSync(resolve(src,"lib/understanding-core/index.ts"),"utf8"),barrelExported=names.some(name=>barrel.includes(name));
  write("phase-5b6-import-isolation-audit.json",{schemaVersion:"lightbi.phase-5b6-import-isolation-audit.v1",sidecarPolicyHash:actualContractSidecarPolicyHash(),allowedImporters:[...allowed].sort(),productionImporters:importers,barrelExported,productionContractsModified:false,UIChanged:false,AIChanged:false,BAChanged:false,DuckDBChanged:false,persistence:false,telemetry:false,featureFlags:false,DOMAIN_SUPPORT_MANIFESTPopulated:false,productionWiring:{executed:false}});
  expect(importers).toEqual([]);expect(barrelExported).toBe(false);
 });
});
