import {describe,expect,it} from "vitest";
import type {RuntimePlanPreview} from "../runtime-planner-preview";
import type {AggregationOriginV1} from "./aggregation-intent-contracts";
import type {Phase4CReadinessReferenceV1,Phase5ACanonicalEnvelopeReferenceV1,Phase5B5ProjectionReferenceV1} from "./actual-contract-sidecar-contracts";
import {ActualSidecarBindingRegistry,captureActualRuntimeContracts,createActualContractSidecar} from "./actual-contract-capture-harness";
import {ACTUAL_CONTRACT_SIDECAR_POLICY,actualContractSidecarPolicyHash} from "./actual-contract-sidecar-policy";

const probes=["plan_without_aggregation","legacy_injected_SUM","explicit_SUM","explicit_AVG","explicit_COUNT","sql_SUM","sql_COUNT","plan_unchanged","sql_unchanged","capability_map_preserved","blockers_preserved","same_sql_different_origin","same_source_concurrent_plans","stale_result_binding","retry_binding","source_hash_mismatch","plan_fingerprint_mismatch","sql_fingerprint_mismatch","missing_canonical_envelope","missing_phase5b5_projection","ambiguous_request_binding","result_without_lineage","chart_association","BA_association","KPI_ineligible","BA_ineligible","narrative_ineligible","no_production_mutation","no_production_imports","no_query_execution","no_persistence_telemetry","diagnostic_provenance","repository_typecheck_gate","no_policy_change","no_authority_migration"] as const;
const hash="a".repeat(64);
const plan=(operator?:"SUM"|"COUNT"|"AVG",id="p1"):RuntimePlanPreview=>({id,sourceIntentId:`intent_${id}`,status:"ready",executionMode:"preview_only",logicalOperations:[{type:"scan",columns:["group","amount"]},{type:"group_by",dimensions:["group"],measures:["amount"],measureAggregations:operator?{amount:operator}:undefined},{type:"limit",rows:100}],requiredColumns:["group","amount"],expectedOutput:{shape:"bar_chart",dimensions:["group"],measures:["amount"]},measureAggregations:operator?{amount:operator}:undefined,warnings:[],blockedReasons:[],source:"runtime_intent"});
const projection=(origin:AggregationOriginV1="automatic_legacy_default"):Phase5B5ProjectionReferenceV1=>({sourceArtifactIdentity:"artifact-1",plan:{lineage:{identity:`lineage-${origin}`,sourceHash:{algorithm:"sha256",value:hash},physicalColumn:"amount",origin:{origin},metricReference:{state:"no_metric",metricId:null,version:null,approved:false,synthetic:false}},restrictions:{schemaVersion:"lightbi.aggregation-restriction-set.v1",identity:"restrictions-1",restrictions:[{code:"NOT_BUSINESS_VERIFIED",reason:"No approved metric.",governedIdentity:"aggregation-restriction:NOT_BUSINESS_VERIFIED"}],absenceIsPermission:false},governance:{requiredEvidence:{metricDefinition:true,measureRole:true,grain:true}},useEligibility:{allowed:["mechanical_preview"],prohibited:["KPI_card","BA_conclusion","narrative"],chartDecisionEligible:false,BAConclusionEligible:false,narrativeEligible:false,recommendationEligible:false,automaticAlertEligible:false,persistedMetricEligible:false,executionAuthorized:false}}});
const capability=(capabilityId:string,state:string)=>({capabilityId,state,governingRuleIds:["rule"],supportingEvidence:[],blockers:[{code:`${capabilityId}_BLOCKED`,severity:"material",capabilityId,references:["evidence"]}],limitations:[{code:"LIMIT",capabilityId,references:["evidence"]}],upstreamDependencies:[],debt:[{code:"DEBT",capabilityId,references:["evidence"]}],requiredRemediation:[{code:"confirm_grain",parameters:{column:"amount"}}],provenance:["canonical"],humanConfirmationRequired:true});
const capabilities=[capability("numeric_aggregation_ready","blocked"),capability("measure_role_assessment_ready","conditionally_ready"),capability("grain_interpretation_ready","blocked")];
const envelope={envelopeIdentity:"envelope-1",capabilities,trustDimensions:[{dimensionId:"aggregation_safety",state:"blocked",ratio:null,numerator:null,denominator:null,numeratorDefinition:null,denominatorDefinition:null,scope:"source",provenance:"canonical_shadow",exclusions:"canonical_contract",unknownHandling:"preserved",limitations:["LIMIT"],debt:["DEBT"]}],blockers:capabilities.flatMap(x=>x.blockers),limitations:[{code:"LIMIT",references:["evidence"]}],debt:[{code:"DEBT",migrationGate:"blocked"}],remediation:[{code:"confirm_grain",parameters:{column:"amount"},capabilityIds:["grain_interpretation_ready"],humanConfirmationRequired:true,trustDependencies:["aggregation_safety"],presentationOnly:true}],restrictions:[],summaryPercentage:null,productionWiring:{executed:false}} as Phase5ACanonicalEnvelopeReferenceV1;
const readiness={identity:{id:"readiness-1",sourceIds:["source"],sourceHashes:[{sourceId:"source",hash}]},capabilities,trustDimensions:[],blockers:capabilities.flatMap(x=>x.blockers),limitations:capabilities.flatMap(x=>x.limitations),debt:capabilities.flatMap(x=>x.debt),requiredRemediation:capabilities.flatMap(x=>x.requiredRemediation),presentationProjection:{presentationOnly:true,decisionAuthority:false,measurableRatios:[],criticalBlockedCapabilities:["numeric_aggregation_ready","grain_interpretation_ready"],summaryPercentage:null,productionWiring:{executed:false}},productionWiring:{executed:false}} as Phase4CReadinessReferenceV1;
const make=(runtimePlan=plan(),origin:AggregationOriginV1="automatic_legacy_default",rows:Record<string,unknown>[]=[{group:"A",amount:10},{group:"B",amount:20}])=>{const capture=captureActualRuntimeContracts(runtimePlan,rows);return{capture,sidecar:createActualContractSidecar({projection:projection(origin),canonicalEnvelope:envelope,readiness,sourceHash:hash,capture})!};};

describe("Phase 5B6 actual runtime contract shadow sidecar",()=>{
 it("enumerates the 35 mandatory probes",()=>expect(probes).toHaveLength(35));
 it("calls the actual bridge and SQL preview for absent, SUM, AVG and COUNT operators",()=>{
  const automatic=make();expect(automatic.sidecar.plan.operator).toBe("SUM");expect(automatic.sidecar.plan.insertions).toEqual([{operationIndex:1,measure:"amount",before:"NONE",after:"SUM"}]);expect(automatic.capture.actualSqlText).toContain("SUM(");
  for(const operator of ["SUM","AVG","COUNT"] as const){const item=make(plan(operator),"explicit_user_selection");expect(item.sidecar.plan.operator).toBe(operator);expect(item.sidecar.plan.insertions).toEqual([]);expect(item.capture.actualSqlText).toContain(operator==="COUNT"?"COUNT(":`${operator}(`);expect(item.sidecar.plan.origin).toBe("explicit_user_selection");}
 });
 it("preserves plans, SQL and complete canonical/readiness records",()=>{
  const runtimePlan=plan(),before=JSON.stringify(runtimePlan),{capture,sidecar}=make(runtimePlan),sql=capture.actualSqlText;
  expect(JSON.stringify(runtimePlan)).toBe(before);expect(capture.actualSqlText).toBe(sql);expect(sidecar.objectMutated).toBe(false);expect(sidecar.sqlMutated).toBe(false);
  expect(sidecar.canonicalReferences.envelope.capabilities).toEqual(envelope.capabilities);expect(sidecar.canonicalReferences.readiness.capabilities).toEqual(readiness.capabilities);expect(sidecar.canonicalReferences.envelope.blockers).toEqual(envelope.blockers);expect(sidecar.canonicalReferences.envelope.debt).toEqual(envelope.debt);expect(sidecar.canonicalReferences.envelope.remediation).toEqual(envelope.remediation);expect(sidecar.canonicalReferences.envelope.summaryPercentage).toBeNull();expect(sidecar.canonicalReferences.readiness.presentationProjection.summaryPercentage).toBeNull();
 });
 it("uses compound identities for concurrent, retry, origin and restriction distinctions",()=>{
  const sum=make(plan("SUM","same"),"automatic_legacy_default"),explicit=make(plan("SUM","same"),"explicit_user_selection"),count=make(plan("COUNT","count"),"explicit_user_selection");
  expect(sum.capture.actualSqlText).toBe(explicit.capture.actualSqlText);expect(sum.sidecar.lineage.bindingIdentity).not.toBe(explicit.sidecar.lineage.bindingIdentity);expect(sum.sidecar.lineage.bindingIdentity).not.toBe(count.sidecar.lineage.bindingIdentity);
  const registry=new ActualSidecarBindingRegistry();const first=registry.register(sum.sidecar);expect(registry.register(sum.sidecar)).toEqual(first);expect(registry.register(explicit.sidecar).state).toBe("ambiguous_binding");expect(registry.resolve(sum.sidecar.request.fingerprint,count.sidecar.lineage.bindingIdentity).state).toBe("stale_or_missing");
 });
 it("fails closed at missing and mismatched boundaries",()=>{
  const {capture,sidecar}=make();expect(createActualContractSidecar({projection:null,canonicalEnvelope:envelope,readiness,sourceHash:hash,capture})).toBeNull();expect(createActualContractSidecar({projection:projection(),canonicalEnvelope:null,readiness,sourceHash:hash,capture})).toBeNull();
  const mismatch=createActualContractSidecar({projection:projection(),canonicalEnvelope:envelope,readiness,sourceHash:"b".repeat(64),capture})!;expect(mismatch.integrity.state).toBe("source_hash_mismatch");expect(mismatch.integrity.failClosed).toBe(true);expect(sidecar.result.availableForSafeInvocation).toBe(false);expect(sidecar.result.missingFields).toContain("lineage");
 });
 it("classifies chart and BA boundaries without granting downstream eligibility",()=>{
  const {capture,sidecar}=make();expect(capture.chartInputFields).toEqual(["previewResult","runtimePlan","analysisLabel"]);expect(capture.BAInputFields).toContain("runtimeIntent");expect(sidecar.consumers.find(x=>x.consumer==="chart")?.classification).toBe("sidecar_association_possible_without_contract_change");expect(sidecar.consumers.find(x=>x.consumer==="BA")?.classification).toBe("requires_explicit_contract_migration");expect(sidecar.intendedDownstreamEligibility.chartDecisionEligible).toBe(false);expect(sidecar.intendedDownstreamEligibility.BAConclusionEligible).toBe(false);expect(sidecar.intendedDownstreamEligibility.narrativeEligible).toBe(false);
 });
 it("executes no query, persistence, telemetry, policy change or authority migration",()=>{
  const {capture,sidecar}=make();expect(capture.queryExecuted).toBe(false);expect(capture.persistenceUsed).toBe(false);expect(capture.telemetryUsed).toBe(false);expect(sidecar.approvalGranted).toBe(false);expect(sidecar.executionAuthorized).toBe(false);expect(sidecar.productionWiring.executed).toBe(false);expect(ACTUAL_CONTRACT_SIDECAR_POLICY.forbiddenEffects).toContain("production_import");expect(actualContractSidecarPolicyHash()).toMatch(/^[a-f0-9]{64}$/);
 });
});
