import {describe,expect,it} from "vitest";
import {readFileSync,readdirSync,statSync,writeFileSync} from "node:fs";
import {resolve,relative} from "node:path";
import type {AggregationIntentBoundaryArtifactV1} from "./aggregation-intent-contracts";
import {projectAggregationRestrictions} from "./aggregation-restriction-projection";
import {AGGREGATION_PROJECTION_POLICY,aggregationProjectionPolicyHash} from "./aggregation-restriction-projection-policy";

const root=resolve(__dirname,"../../../../.."),docs=resolve(root,"docs/architecture"),src=resolve(root,"apps/desktop/src");
const read=(name:string)=>JSON.parse(readFileSync(resolve(docs,name),"utf8"));
const write=(name:string,value:unknown)=>writeFileSync(resolve(docs,name),JSON.stringify(value,null,2)+"\n");
const walk=(dir:string):string[]=>readdirSync(dir).flatMap(name=>{const path=resolve(dir,name);return statSync(path).isDirectory()?walk(path):[path]});
type Replay={policyHash:string;counts:{raw:number;unique:number;duplicates:number;automaticSumConflicts:number;informationalNonSum:number};artifacts:AggregationIntentBoundaryArtifactV1[]};
const restrictionCodes=["EXPLORATORY_ONLY","NOT_BUSINESS_VERIFIED","NOT_ELIGIBLE_FOR_CHART_DECISION_USE","NOT_ELIGIBLE_FOR_BA_CONCLUSION","NOT_ELIGIBLE_FOR_NARRATIVE_CLAIM","NOT_ELIGIBLE_FOR_AUTOMATIC_ALERT","NOT_ELIGIBLE_FOR_PERSISTED_METRIC","REQUIRES_EXPLICIT_ACKNOWLEDGEMENT","REQUIRES_METRIC_DEFINITION","REQUIRES_MEASURE_ROLE","REQUIRES_GRAIN_CONFIRMATION","REQUIRES_AGGREGATION_RULE","REQUIRES_REPEATED_TOTAL_RULE","REQUIRES_SNAPSHOT_TIME_RULE","REQUIRES_NON_ADDITIVE_FORMULA","REQUIRES_VALID_CANONICAL_ENVELOPE"];
const requirementMap={measureRole:"REQUIRES_MEASURE_ROLE",grain:"REQUIRES_GRAIN_CONFIRMATION",nonAdditiveFormula:"REQUIRES_NON_ADDITIVE_FORMULA",repeatedTotal:"REQUIRES_REPEATED_TOTAL_RULE",snapshotTime:"REQUIRES_SNAPSHOT_TIME_RULE",metricDefinition:"REQUIRES_METRIC_DEFINITION",acknowledgement:"REQUIRES_EXPLICIT_ACKNOWLEDGEMENT"} as const;
const consumers=[
 ["plan_preview",["lineage","restrictions","origin","operator"],["decision_chart","BA_conclusion"],false,false],
 ["SQL_preview",["lineage","restrictions","origin","operator","metricReference"],["BA_conclusion"],false,false],
 ["backend_execution_request",["lineage","restrictions","useEligibility"],["execution_authority"],false,false],
 ["execution_result",["lineage","restrictions","executionProvenance"],["BA_conclusion"],false,false],
 ["chart_preview",["lineage","restrictions","machineReadableRestrictions"],["decision_chart","KPI_card"],true,false],
 ["KPI_card",["lineage","restrictions","approvedMetricReference"],["KPI_card"],false,true],
 ["BA_decision_brief",["lineage","restrictions","approvedMetricReference"],["BA_conclusion"],false,true],
 ["narrative_generation",["lineage","restrictions","approvedMetricReference"],["narrative"],false,true],
 ["recommendation",["lineage","restrictions","approvedMetricReference"],["recommendation"],false,true],
 ["automated_alert",["lineage","restrictions","approvedMetricReference"],["automatic_alert"],false,true],
 ["persisted_metric",["lineage","restrictions","approvedMetricReference"],["persisted_metric"],false,true]
] as const;

describe("Phase 5B5 governed projection replay",()=>{
 it("projects all 145 governed records losslessly and writes audits",()=>{
  const source=read("phase-5b4-unique-divergence-policy-replay.json") as Replay;
  expect(source.artifacts).toHaveLength(145);expect(source.counts).toEqual({raw:291,unique:145,duplicates:146,automaticSumConflicts:136,informationalNonSum:9});
  const artifacts=source.artifacts.map(artifact=>projectAggregationRestrictions({artifact}));
  const count=(fn:(item:typeof artifacts[number])=>boolean)=>artifacts.filter(fn).length;
  const identities=artifacts.map(x=>x.sourceArtifactIdentity),restrictionDistribution=Object.fromEntries(restrictionCodes.map(code=>[code,count(x=>x.plan.restrictions.restrictions.some(r=>r.code===code))]));
  const requirements=artifacts.map(item=>({identity:item.sourceArtifactIdentity,requirements:Object.entries(requirementMap).filter(([,code])=>item.plan.restrictions.restrictions.some(r=>r.code===code)).map(([key])=>key)}));
  const requirementCounts=Object.fromEntries(Object.keys(requirementMap).map(key=>[key,requirements.filter(x=>x.requirements.includes(key)).length]));
  const keys=Object.keys(requirementMap),intersections=Object.fromEntries(keys.flatMap((a,i)=>keys.slice(i+1).map(b=>[`${a}&${b}`,requirements.filter(x=>x.requirements.includes(a)&&x.requirements.includes(b)).length])));
  write("phase-5b5-aggregation-restriction-projection-replay.json",{schemaVersion:"lightbi.phase-5b5-projection-replay.v1",sourcePolicyHash:source.policyHash,projectionPolicyHash:aggregationProjectionPolicyHash(),counts:source.counts,summary:{validPlanProjections:count(x=>x.plan.integrity.state==="valid"),automaticDefaultsProhibited:count(x=>x.plan.futureGovernedBoundaryWouldProhibitInjection),explicitIntentRecords:count(x=>x.plan.lineage.origin.explicit),SQLPreviewProjectionEligible:count(x=>x.sqlPreview.integrity.state==="valid"),exploratoryChartDisplayCandidates:count(x=>x.chart.compatibility==="restricted_display_with_warning"),decisionChartIneligible:count(x=>!x.chart.useEligibility.chartDecisionEligible),BAIneligible:count(x=>!x.BA.useEligibility.BAConclusionEligible),narrativeIneligible:count(x=>!x.BA.useEligibility.narrativeEligible),alertIneligible:count(x=>!x.BA.useEligibility.automaticAlertEligible),persistenceIneligible:count(x=>!x.BA.useEligibility.persistedMetricEligible),missingMeasureRoleEvidence:requirementCounts.measureRole,missingGrainEvidence:requirementCounts.grain,missingMetricDefinitions:requirementCounts.metricDefinition,nonAdditiveRestrictions:requirementCounts.nonAdditiveFormula,projectionIntegrityFailures:count(x=>x.plan.integrity.state!=="valid"),projectionLossCount:artifacts.reduce((sum,x)=>sum+x.projectionLossCount,0)},restrictionSetDistribution:restrictionDistribution,lineageIdentities:artifacts.map(x=>({identity:x.sourceArtifactIdentity,lineageIdentity:x.plan.lineage.identity,restrictionSetIdentity:x.plan.restrictions.identity,origin:x.plan.lineage.origin.origin})),artifacts,rawIdentitiesPreserved:new Set(identities).size===145,rawObservationsModified:false,productionImpactClaim:false,accuracyClaim:false,summaryPercentage:null,productionWiring:{executed:false}});
  write("phase-5b5-requirement-intersection-audit.json",{schemaVersion:"lightbi.phase-5b5-requirement-intersection.v1",requirements,individualCounts:requirementCounts,pairIntersections:intersections,recordsWithMultipleRequirements:requirements.filter(x=>x.requirements.length>1).length,recordsWithOnlyOneRequirement:requirements.filter(x=>x.requirements.length===1).length,recordsWithNoRecordedRequirement:requirements.filter(x=>x.requirements.length===0).length,recordsWithInsufficientGranularEvidence:requirements.filter(x=>x.requirements.includes("measureRole")||x.requirements.includes("grain")).length,requirementsIndependentOverlappingOrConditional:true,exclusivityInferredFromAggregateCounts:false});
  write("phase-5b5-production-contract-loss-audit.json",{schemaVersion:"lightbi.phase-5b5-production-contract-loss-audit.v1",transitions:[
   {id:"numeric_health_to_guarded_plan",producer:"numeric-health-gate.evaluateNumericHealth",consumer:"guarded-sum-bridge.enhancePlanWithGuardedSum",actualContract:"ColumnNumericHealth -> RuntimePlanPreview",operator:"physical SUM/AVG/COUNT support; bridge may inject SUM or COUNT",preserved:["physical column name","physical parse decision"],lost:["aggregation origin","metric identity","measure role","grain","restrictions","acknowledgement","decision-use eligibility","canonical provenance"],lossClasses:["aggregation_origin_loss","metric_identity_loss","measure_role_loss","grain_context_loss","restriction_loss","acknowledgement_loss","decision_use_boundary_loss","authority_escalation_risk"],userVisibleOrAuthorityBearing:true},
   {id:"guarded_plan_to_SQL_preview",producer:"guarded-sum-bridge.enhancePlanWithGuardedSum",consumer:"safe-sql-preview.createSafeSqlPreview",actualContract:"RuntimePlanPreview -> SafeSqlPreview",operator:"operator encoded only in SQL",preserved:["plan id","referenced columns","SQL operator text"],lost:["origin","metric identity","grain","measure role","restrictions","acknowledgement","result-use eligibility"],lossClasses:["aggregation_origin_loss","metric_identity_loss","grain_context_loss","measure_role_loss","restriction_loss","acknowledgement_loss","decision_use_boundary_loss"],userVisibleOrAuthorityBearing:true},
   {id:"SQL_preview_to_backend_request",producer:"Investigation.handleRunPreview",consumer:"backend-preview-executor.executeBackendPreview",actualContract:"SafeSqlPreview plus unenhanced RuntimePlanPreview and source rows -> BackendPreviewExecutionResult",operator:"SQL from enhanced plan; request runtime plan is unenhanced",preserved:["SQL text","source id","requested columns"],lost:["operator-origin linkage","canonical provenance","restrictions","metric identity"],lossClasses:["provenance_loss","aggregation_origin_loss","restriction_loss","metric_identity_loss","authority_escalation_risk"],userVisibleOrAuthorityBearing:true},
   {id:"backend_to_local_result",producer:"backend-preview-executor.executeBackendPreview/local-duckdb-executor",consumer:"Investigation.handleRunPreview",actualContract:"BackendPreviewExecutionInput -> DuckDBPreviewResult",operator:"executed from SQL only",preserved:["rows","columns","execution warnings"],lost:["aggregation lineage","origin","metric identity","grain","measure role","restrictions","decision-use boundary"],lossClasses:["provenance_loss","aggregation_origin_loss","metric_identity_loss","grain_context_loss","measure_role_loss","restriction_loss","decision_use_boundary_loss"],userVisibleOrAuthorityBearing:true},
   {id:"result_to_chart",producer:"Investigation.handleRunPreview",consumer:"chart-preview-model.createChartPreviewModel",actualContract:"DuckDBPreviewResult + unenhanced RuntimePlanPreview -> ChartPreviewModel",operator:"not governed in result contract",preserved:["rows","display dimensions/measures"],lost:["origin","metric identity","restrictions","authority provenance"],lossClasses:["aggregation_origin_loss","metric_identity_loss","restriction_loss","decision_use_boundary_loss","authority_escalation_risk"],userVisibleOrAuthorityBearing:true},
   {id:"result_to_BA_and_persistence",producer:"Investigation/createChartPreviewModel",consumer:"ba-decision-engine.createBADecisionBrief and chart/session persistence",actualContract:"preview rows/chart model/briefing -> BA brief, recommendation, saved chart/session",operator:"not governed downstream",preserved:["display data","basic runtime metadata"],lost:["machine-readable restrictions","metric approval","origin","grain/measure-role lineage"],lossClasses:["restriction_loss","metric_identity_loss","aggregation_origin_loss","grain_context_loss","measure_role_loss","decision_use_boundary_loss","authority_escalation_risk"],userVisibleOrAuthorityBearing:true}
  ],acknowledgementMetadataPresent:false,structuredRestrictionContractPresent:false,productionContractsModified:false});
  write("phase-5b5-consumer-compatibility-matrix.json",{schemaVersion:"lightbi.phase-5b5-consumer-compatibility-matrix.v1",consumers:consumers.map(([consumer,requiredFields,prohibitedUse,acknowledgementMatters,approvedMetricMandatory])=>({consumer,requiredProjectionFields:requiredFields,prohibitedMissingFields:requiredFields,minimumIntegrityState:"valid",permittedUseClasses:consumer==="chart_preview"?["exploratory_display"]:consumer==="plan_preview"||consumer==="SQL_preview"?["mechanical_preview"]:[],prohibitedUseClasses:prohibitedUse,acknowledgementMatters,approvedMetricEvidenceMandatory:approvedMetricMandatory,currentContractSupportsProjection:false,migrationDebt:"production contract lacks structured aggregation lineage/restrictions"})),productionConsumersModified:false});
  const strategies=["restriction_metadata_only","metadata_plus_visible_warning","metadata_plus_acknowledgement_boundary","hard_prohibition_automatic_defaults","governed_metric_only_BA_boundary","retain_current_contracts"];
  write("phase-5b5-projection-strategy-audit.json",{schemaVersion:"lightbi.phase-5b5-projection-strategy-audit.v1",strategies:strategies.map(strategy=>({strategy,surfaces:consumers.map(([consumer])=>({consumer,safetyProperties:strategy==="retain_current_contracts"?[]:["origin preserved","restrictions machine-readable"],metadataRequirements:["lineage","restriction set","use eligibility","integrity"],UXImplications:strategy.includes("warning")?"later visible warning required":"no Phase 5B5 UI effect",residualRisk:strategy==="retain_current_contracts"?"authority metadata remains lost":"production migration and consumer enforcement remain unresolved",losslessness:strategy==="retain_current_contracts"?"lossy":"possible_with_versioned_projection",authorityImplications:"none in Phase 5B5",implementationPrerequisites:["versioned production contract migration","consumer enforcement","regression approval"],suitabilityForLaterControlledProjection:strategy!=="retain_current_contracts"})),selectedForProduction:false})),productionStrategySelected:null});
  write("phase-5b5-migration-gate-audit.json",{schemaVersion:"lightbi.phase-5b5-migration-gate.v1",restrictionProjectionContractComplete:true,restrictionProjectionLosslessOnGovernedReplay:true,planProjectionCompatible:true,SQLPreviewProjectionCompatible:true,chartProjectionCompatible:true,BAProjectionCompatible:true,consumerContractMigrationDebtDispositioned:true,automaticSumConflictCoverageComplete:true,criticalAggregationDivergencesResolved:false,aggregationRestrictionProjectionEligible:true,productionProjectionEligible:false,authorityMigrationEvidenceSufficientForPhase5CPlanning:false,canonicalAuthorityMigrationEligible:false,finalWorktreeFullSuiteVerified:false,summaryPercentage:null,productionWiring:{executed:false},phase5CStarted:false});
  expect(new Set(identities).size).toBe(145);expect(count(x=>x.plan.integrity.state==="valid")).toBe(145);expect(count(x=>x.plan.futureGovernedBoundaryWouldProhibitInjection)).toBe(136);expect(count(x=>x.BA.useEligibility.BAConclusionEligible)).toBe(0);expect(artifacts.every(x=>x.projectionLossCount===0&&!x.operationApproval.executed&&!x.metricApproval.executed&&!x.productionWiring.executed)).toBe(true);
 });

 it("proves import and production isolation",()=>{
  const names=["aggregation-restriction-projection-contracts","aggregation-restriction-projection-policy","aggregation-restriction-projection"];
  const allowed=new Set(["aggregation-restriction-projection.test.ts","aggregation-restriction-projection.corpus.test.ts","aggregation-restriction-projection.ts","aggregation-restriction-projection-policy.ts","aggregation-restriction-projection-contracts.ts"]);
  const importers=walk(src).filter(path=>/\.(ts|tsx)$/.test(path)).filter(path=>names.some(name=>readFileSync(path,"utf8").includes(name))).map(path=>relative(src,path)).filter(path=>!allowed.has(path.split("/").at(-1)!));
  const barrel=readFileSync(resolve(src,"lib/understanding-core/index.ts"),"utf8"),barrelExported=names.some(name=>barrel.includes(name));
  write("phase-5b5-import-isolation-audit.json",{schemaVersion:"lightbi.phase-5b5-import-isolation-audit.v1",projectionPolicyHash:aggregationProjectionPolicyHash(),allowedImporters:[...allowed].sort(),productionImporters:importers,barrelExported,persistence:false,telemetry:false,featureFlags:false,UIChanged:false,productionFilesModified:false,productionWiring:{executed:false}});
  expect(importers).toEqual([]);expect(barrelExported).toBe(false);expect(AGGREGATION_PROJECTION_POLICY.schemaVersion).toBe("lightbi.aggregation-restriction-projection-policy.v1");
 });
});
