import type {AggregationIntentBoundaryArtifactV1,AggregationOriginV1,AggregationResultRestrictionV1,RequiredMetricEvidenceV1} from "./aggregation-intent-contracts";

export const AGGREGATION_PROJECTION_CONTRACT_VERSION="lightbi.aggregation-restriction-projection.v1" as const;
export const AGGREGATION_PROJECTION_POLICY_VERSION="lightbi.aggregation-restriction-projection-policy.v1" as const;

export type AggregationProjectionRestrictionCodeV1=AggregationResultRestrictionV1["code"]|"NOT_ELIGIBLE_FOR_CHART_DECISION_USE"|"REQUIRES_AGGREGATION_RULE";
export type AggregationProjectionIntegrityStateV1="valid"|"incomplete_lineage"|"missing_restrictions"|"policy_mismatch"|"source_hash_mismatch"|"aggregation_origin_unknown"|"metric_reference_invalid"|"use_boundary_inconsistent"|"privacy_violation"|"unsupported_contract";
export type AggregationProjectionStageV1="plan"|"sql_preview"|"result"|"chart"|"BA";
export type AggregationUseClassProjectionV1="mechanical_preview"|"exploratory_display"|"decision_chart"|"KPI_card"|"BA_evidence"|"BA_conclusion"|"narrative"|"recommendation"|"automatic_alert"|"persisted_metric";
export type AggregationChartCompatibilityV1="render_eligible"|"exploratory_display_only"|"restricted_display_with_warning"|"decision_chart_ineligible"|"invalid_projection";
export type AggregationBACompatibilityV1="BA_INELIGIBLE"|"BA_EVIDENCE_ONLY_WITH_RESTRICTIONS"|"BA_ELIGIBLE_GOVERNED_METRIC"|"NARRATIVE_INELIGIBLE"|"ALERT_INELIGIBLE"|"PERSISTED_METRIC_INELIGIBLE";

export type AggregationRestrictionV1={code:AggregationProjectionRestrictionCodeV1;reason:string;governedIdentity:string};
export type AggregationRestrictionSetV1={schemaVersion:"lightbi.aggregation-restriction-set.v1";identity:string;restrictions:AggregationRestrictionV1[];absenceIsPermission:false};
export type AggregationOriginTraceV1={origin:AggregationOriginV1;automatic:boolean;explicit:boolean;recommended:boolean;imported:boolean;metricGoverned:boolean;unknown:boolean};
export type AggregationMetricReferenceV1=
 |{state:"no_metric";metricId:null;version:null;approved:false;synthetic:false}
 |{state:"metric_candidate_unapproved";metricId:string;version:string|null;approved:false;synthetic:boolean}
 |{state:"approved_metric_reference";metricId:string;version:string;approved:true;synthetic:boolean;approvalEvidenceId:string};
export type AggregationUseEligibilityV1={allowed:AggregationUseClassProjectionV1[];prohibited:AggregationUseClassProjectionV1[];chartDecisionEligible:false;BAConclusionEligible:false;narrativeEligible:false;recommendationEligible:false;automaticAlertEligible:false;persistedMetricEligible:false;executionAuthorized:false};
export type AggregationProjectionIntegrityV1={state:AggregationProjectionIntegrityStateV1;failClosed:boolean;reasons:string[]};
export type AggregationLineageEnvelopeV1={schemaVersion:"lightbi.aggregation-lineage-envelope.v1";identity:string;sourceIdentity:string;sourceHash:{algorithm:"sha256";value:string};physicalColumnIndex:number;physicalColumn:string;expression:string|null;operator:"SUM"|"AVG"|"COUNT"|"NONE"|"UNKNOWN";countSemantics:AggregationIntentBoundaryArtifactV1["intent"]["countSemantics"];origin:AggregationOriginTraceV1;groupingDimensions:string[];filterSemantics:string[];timeBasis:string|null;metricReference:AggregationMetricReferenceV1;restrictionSetIdentity:string;upstreamArtifactVersion:string;upstreamPolicyIdentities:{aggregationIntentPolicyVersion:string;aggregationIntentPolicyHash:string;projectionPolicyVersion:string;projectionPolicyHash:string}};
export type AggregationProjectionLimitationV1={code:string;message:string;blocksAuthority:true};
export type AggregationProjectionDebtV1={code:string;stage:AggregationProjectionStageV1;severity:"caution"|"material"|"critical";blocksProductionMigration:true};

export type AggregationGovernanceContextV1={canonicalCapabilityStates:Record<string,string>;canonicalCapabilityStateSource:"provided"|"not_retained_by_upstream_contract";measureRoleState:"present_unresolved"|"resolved"|"absent";grainState:"confirmed"|"ambiguous"|"unknown";repeatedParentRisk:"present"|"not_established";snapshotRisk:"present"|"not_established";nonAdditiveRisk:"present"|"not_established";requiredEvidence:RequiredMetricEvidenceV1;acknowledgementState:"absent"|"present_exploratory_only"};
type ProjectionBase={schemaVersion:typeof AGGREGATION_PROJECTION_CONTRACT_VERSION;stage:AggregationProjectionStageV1;lineage:AggregationLineageEnvelopeV1;restrictions:AggregationRestrictionSetV1;governance:AggregationGovernanceContextV1;useEligibility:AggregationUseEligibilityV1;integrity:AggregationProjectionIntegrityV1;limitations:AggregationProjectionLimitationV1[];debt:AggregationProjectionDebtV1[];shadowOnly:true;approvalGranted:false;executionAuthorized:false;productionWiring:{executed:false}};
export type AggregationPlanProjectionV1=ProjectionBase&{stage:"plan";rawIncomingPlan:unknown;observedAggregation:{operator:AggregationLineageEnvelopeV1["operator"];origin:AggregationOriginV1};intentClassification:AggregationIntentBoundaryArtifactV1["disposition"];requiredEvidence:RequiredMetricEvidenceV1;legacyBridgeWouldInjectOperator:boolean;futureGovernedBoundaryWouldProhibitInjection:boolean;planMutated:false};
export type AggregationSqlPreviewProjectionV1=ProjectionBase&{stage:"sql_preview";sqlFingerprint:string|null;sqlTextRetained:false;syntaxOrGenerationStatus:"not_observed"|"observed_ready"|"observed_blocked";sqlTextSufficientForAuthorityReconstruction:false;sqlChanged:false};
export type AggregationResultProjectionV1=ProjectionBase&{stage:"result";executionStatus:"not_executed"|"success_observed"|"failure_observed";rowPresence:"not_observed"|"empty_observed"|"non_empty_observed";executionProvenance:string|null;rowsRetained:false};
export type AggregationChartProjectionV1=ProjectionBase&{stage:"chart";compatibility:AggregationChartCompatibilityV1;machineReadableRestrictions:true;KPIUseEligible:false;formattingGrantsAuthority:false};
export type AggregationBAProjectionV1=ProjectionBase&{stage:"BA";compatibility:AggregationBACompatibilityV1[];rawRowsConvertedToConclusion:false;outputGenerated:false};
export type AggregationRestrictionProjectionArtifactV1={schemaVersion:typeof AGGREGATION_PROJECTION_CONTRACT_VERSION;sourceArtifactIdentity:string;plan:AggregationPlanProjectionV1;sqlPreview:AggregationSqlPreviewProjectionV1;result:AggregationResultProjectionV1;chart:AggregationChartProjectionV1;BA:AggregationBAProjectionV1;projectionLossCount:number;rawInputPreserved:true;operationApproval:{executed:false};metricApproval:{executed:false};canonicalAuthorityMigrationEligible:false;productionWiring:{executed:false}};
export type AggregationProjectionPolicyV1={schemaVersion:typeof AGGREGATION_PROJECTION_POLICY_VERSION;requiredRestrictions:AggregationProjectionRestrictionCodeV1[];restrictionRules:string[];lineageFields:string[];privacyForbidden:string[];authorityRules:string[];forbiddenEffects:string[]};

export type AggregationProjectionInputV1={artifact:AggregationIntentBoundaryArtifactV1;rawIncomingPlan?:unknown;canonicalCapabilityStates?:Record<string,string>;groupingDimensions?:string[];filterSemantics?:string[];timeBasis?:string|null;metricReference?:AggregationMetricReferenceV1;sqlText?:string|null;sqlStatus?:AggregationSqlPreviewProjectionV1["syntaxOrGenerationStatus"];executionObservation?:{status:"success_observed"|"failure_observed";rowPresence:"empty_observed"|"non_empty_observed";provenance:string|null};additionalRestrictions?:AggregationResultRestrictionV1[]};
