import {deterministicPolicySha256} from "./contextual-evidence-policy";
import {AGGREGATION_INTENT_POLICY_VERSION,type AggregationAuthorityTaxonomyEntryV1,type AggregationIntentPolicyV1,type RequiredMetricEvidenceV1} from "./aggregation-intent-contracts";

const t=(useClass:AggregationAuthorityTaxonomyEntryV1["useClass"],chosenBy:string,explicit:boolean|"depends",authorityLevel:AggregationAuthorityTaxonomyEntryV1["authorityLevel"],requiredEvidence:string[],allowedOutputUse:string[],prohibitedOutputUse:string[],confirmationRequired:boolean,metricSemanticsRequired:boolean,canonicalApprovalEventuallyRequired:boolean,residualRisk:string[]):AggregationAuthorityTaxonomyEntryV1=>({useClass,chosenBy,explicit,authorityLevel,requiredEvidence,allowedOutputUse,prohibitedOutputUse,confirmationRequired,metricSemanticsRequired,canonicalApprovalEventuallyRequired,residualRisk});
export const AGGREGATION_AUTHORITY_TAXONOMY:AggregationAuthorityTaxonomyEntryV1[]=[
 t("physical_operator_supported","physical profiler",false,"observation",["parse evidence"],["operator feasibility observation"],["business metric claim"],false,false,true,["physical support is not semantic additivity"]),
 t("descriptive_row_count","explicit user or governed planner","depends","exploratory_choice",["count semantics","row scope"],["restricted descriptive preview"],["entity count without governed key"],true,false,true,["duplicates and repeated periods"]),
 t("explicit_exploratory_aggregation","user",true,"exploratory_choice",["acknowledgement","restrictions"],["future restricted exploratory preview"],["BA conclusion","narrative","alert","persisted metric"],true,true,true,["consent is not correctness"]),
 t("planner_recommendation","planner",false,"recommendation",["unresolved evidence","risk disclosure"],["recommendation display"],["selection","execution","decision claim"],false,true,true,["recommendation may be semantically wrong"]),
 t("automatic_default_aggregation","legacy runtime",false,"observation",["governed metric contract"],[],["silent selection","execution","decision use"],false,true,true,["silent semantic choice"]),
 t("governed_metric_aggregation","metric owner","depends","governed_candidate",["complete approved metric evidence"],["future controlled projection candidate"],["use before canonical approval"],false,true,true,["contract compatibility and version drift"]),
 t("chart_display_use","chart consumer","depends","decision_use",["result restrictions"],["restricted display only"],["decision-safe implication"],false,true,true,["display can imply false confidence"]),
 t("BA_decision_use","BA consumer","depends","decision_use",["approved metric","canonical readiness"],[],["ungoverned conclusion","ranking","recommendation"],false,true,true,["downstream restriction loss"]),
 t("narrative_use","narrative consumer","depends","decision_use",["approved metric","canonical readiness"],[],["ungoverned trend or claim"],false,true,true,["language can overstate evidence"]),
 t("execution_authority","runtime authority","depends","execution",["canonical operation approval"],[],["shadow authorization"],false,true,true,["execution does not establish correctness"]),
 t("unknown_origin","unknown",false,"unknown",["origin resolution"],[],["selection","execution","decision use"],false,true,true,["authority cannot be inferred from operator"])
];
export const EMPTY_REQUIRED_METRIC_EVIDENCE=():RequiredMetricEvidenceV1=>({stableMetricIdAndVersion:false,measureSemanticRole:false,aggregationOperator:false,sourceGrainRequirement:false,groupingDimensions:false,numeratorDenominator:false,timeBehavior:false,additivityRule:false,repeatedParentHandling:false,snapshotHandling:false,nullHandling:false,duplicateHandling:false,unitCurrencyBehavior:false,scope:false,provenance:false,approvalStatus:false});
export const AGGREGATION_INTENT_POLICY:AggregationIntentPolicyV1={schemaVersion:AGGREGATION_INTENT_POLICY_VERSION,taxonomy:AGGREGATION_AUTHORITY_TAXONOMY,countRules:["COUNT(*) is descriptive row counting, not entity counting","COUNT(column) excludes nulls","COUNT(DISTINCT key) requires a governed key","row and entity counts must preserve duplicate, snapshot and repeated-period risk","automatic SUM-to-COUNT substitution is prohibited"],consentCorrectnessRules:["userIntentKnown, exploratoryExecutionConsent and businessCorrectnessEstablished are independent","acknowledgement never establishes business correctness","acknowledgement never changes semantic or grain resolution","acknowledgement never grants BA, narrative, alert or persisted-metric eligibility","acknowledgement contains no raw sensitive values"],restrictionRules:["restriction absence is not permission","chart displayability is not decision safety","ungoverned results remain identifiable downstream","BA and narrative eligibility require approved governed metric evidence"],forbiddenEffects:["mutate_runtime_plan","change_generated_sql","approve_operation","execute_metric","activate_domain","wire_production","persist_acknowledgement","emit_telemetry","infer_authority_from_operator","replace_sum_with_count"]};
export const aggregationIntentPolicyHash=(value:unknown=AGGREGATION_INTENT_POLICY)=>deterministicPolicySha256(value);
