import {describe,expect,it} from "vitest";import {readFileSync,writeFileSync} from "node:fs";import {resolve} from "node:path";import {simulateAggregationGuard} from "./aggregation-guard-shadow";import type {AggregationGuardInputV1} from "./aggregation-guard-shadow-contracts";import {aggregationGuardPolicyHash} from "./aggregation-guard-shadow-policy";import {comparisonPolicyHash} from "./legacy-canonical-comparison-policy";
const root=resolve(__dirname,"../../../../..");const docs=resolve(root,"docs/architecture");const read=(name:string)=>JSON.parse(readFileSync(resolve(docs,name),"utf8"));const write=(name:string,value:unknown)=>writeFileSync(resolve(docs,name),JSON.stringify(value,null,2)+"\n");
type Record5B2={divergenceIdentity:string;sourceIdentity:string;sourceHash:{algorithm:"sha256";value:string};physicalColumnIndex:number;physicalColumn:string;legacyResult:Record<string,unknown>;legacyAuthorityClass:string;consumers:string[];sumDefaulted:boolean;sumExecutedByPreviewPath:boolean;canonicalState:"blocked";canonicalBlockers:Array<{code:string}>;risks:string[];disposition:string};
const classifyRole=(name:string)=>/percent|percentage|rate|ratio|margin/i.test(name)?"rate":/average|avg/i.test(name)?"average":/unit.?price|price/i.test(name)?"unit_price":/balance|stock.?value|ending/i.test(name)?"balance":"unknown";
const toInput=(r:Record5B2):AggregationGuardInputV1=>({sourceIdentity:r.sourceIdentity,sourceHash:r.sourceHash,physicalColumnIndex:r.physicalColumnIndex,physicalColumn:r.physicalColumn,legacyNumericHealth:r.legacyResult,intent:r.sumDefaulted?{operator:"SUM",origin:"automatic_default",explicit:false,automaticallyDefaulted:true}:{operator:"NONE",origin:"none",explicit:false,automaticallyDefaulted:false},canonical:{envelopeValid:true,capabilityStates:{measure_role_assessment_ready:"blocked",numeric_aggregation_ready:r.canonicalState,repeated_measure_protection_ready:"blocked",snapshot_time_aggregation_ready:"blocked"},measurePresent:true,measureRole:classifyRole(r.physicalColumn),grainState:"unknown",repeatedParentRisk:r.risks.some(x=>/repeat/i.test(x)),snapshotRisk:r.risks.some(x=>/snapshot/i.test(x)),limitations:r.canonicalBlockers.map(x=>x.code),risks:r.risks},authority:r.sumExecutedByPreviewPath?"execution_candidate":"user_visible_preview"});
const strategies=[
 {id:"warning_only",blocksSilentSum:false,permitsUnsafeExplicit:true,safety:"observability only",remainingRisks:["silent SUM continues"],ux:"warning",authority:"legacy unchanged",requiredEvidence:[],laterProjection:false},
 {id:"require_explicit_user_confirmation",blocksSilentSum:true,permitsUnsafeExplicit:true,safety:"removes silent choice, not semantic risk",remainingRisks:["confirmation is not correctness"],ux:"confirmation step",authority:"user choice remains uncertified",requiredEvidence:["REQUIRE_EXPLICIT_USER_CONFIRMATION"],laterProjection:true},
 {id:"prohibit_automatic_default_but_allow_explicit_choice",blocksSilentSum:true,permitsUnsafeExplicit:true,safety:"blocks default injection",remainingRisks:["unsafe explicit aggregation remains"],ux:"aggregation selection required",authority:"explicit choice only",requiredEvidence:["REQUIRE_AGGREGATION_RULE"],laterProjection:true},
 {id:"require_governed_metric_semantics",blocksSilentSum:true,permitsUnsafeExplicit:false,safety:"requires governed formula and grain",remainingRisks:["metric catalog completeness"],ux:"metric unavailable until governed",authority:"canonical metric contract",requiredEvidence:["REQUIRE_METRIC_DEFINITION","REQUIRE_GRAIN_CONFIRMATION"],laterProjection:true},
 {id:"canonical_restriction_projection",blocksSilentSum:true,permitsUnsafeExplicit:false,safety:"projects canonical blockers",remainingRisks:["projection drift"],ux:"blocked states surfaced",authority:"future controlled boundary",requiredEvidence:["REQUIRE_VALID_CANONICAL_ENVELOPE","REQUIRE_AGGREGATION_RULE"],laterProjection:true},
 {id:"retain_legacy_behavior",blocksSilentSum:false,permitsUnsafeExplicit:true,safety:"none beyond current parsing",remainingRisks:["all current semantic aggregation risks"],ux:"unchanged",authority:"legacy",requiredEvidence:[],laterProjection:false}
];
describe("Phase 5B3 authentic shadow replay",()=>{it("replays governed observations and writes deterministic audits",()=>{const source=read("phase-5b2-aggregation-divergence-disposition.json") as {records:Record5B2[];summary:{critical:number;informational:number}};expect(source.records).toHaveLength(145);expect(source.summary).toEqual({critical:136,informational:9});const artifacts=source.records.map(r=>simulateAggregationGuard(toInput(r)));const byDisposition=Object.fromEntries([...new Set(artifacts.map(x=>x.disposition))].sort().map(k=>[k,artifacts.filter(x=>x.disposition===k).length]));const evidence:Record<string,number>={};for(const a of artifacts)for(const e of a.requiredEvidence)evidence[e.code]=(evidence[e.code]??0)+1;
 write("phase-5b3-aggregation-guard-shadow-replay.json",{schemaVersion:"lightbi.phase-5b3-shadow-replay.v1",policyHash:aggregationGuardPolicyHash(),comparisonPolicy:{version:"lightbi.legacy-canonical-comparison-policy.v2",sha256:comparisonPolicyHash()},authenticObservationCounts:{raw:291,unique:145,duplicates:146,automaticSumConflicts:136,informationalNonSum:9},dedupIdentity:"governed Phase 5B2 divergenceIdentity",artifacts,summary:{byDisposition,automaticSumCasesFutureGuardWouldBlock:artifacts.filter(x=>x.incomingIntent.automaticallyDefaulted&&x.canonicalRestriction.capabilityStates.numeric_aggregation_ready!=="ready").length,explicitAggregationCases:artifacts.filter(x=>x.incomingIntent.explicit).length,physicalOperatorOnlyCases:artifacts.filter(x=>x.disposition==="physical_operator_only").length,noMeasureCases:artifacts.filter(x=>x.disposition==="no_measure_not_applicable").length,requiredEvidence:evidence,repeatedParentRisks:artifacts.filter(x=>x.canonicalRestriction.repeatedParentRisk).length,snapshotRisks:artifacts.filter(x=>x.canonicalRestriction.snapshotRisk).length,nonAdditiveRisks:artifacts.filter(x=>["percentage","rate","average","unit_price","balance"].includes(x.canonicalRestriction.measureRole)).length,unresolvedGrain:artifacts.filter(x=>x.canonicalRestriction.grainState!=="confirmed").length,unresolvedMeasureRole:artifacts.filter(x=>x.canonicalRestriction.measureRole==="unknown").length,invalidEnvelopes:artifacts.filter(x=>!x.canonicalRestriction.envelopeValid).length,previewOnly:artifacts.filter(x=>x.authority==="internal_preview_only"||x.authority==="user_visible_preview").length,executionCapable:artifacts.filter(x=>x.authority==="execution_candidate"||x.authority==="direct_execution").length},accuracyClaim:false,productionImpactClaim:false,productionBehaviorChanged:false});
 write("phase-5b3-preview-execution-authority-audit.json",{schemaVersion:"lightbi.phase-5b3-authority-audit.v1",paths:[{consumer:"Investigation technical SQL details",classification:"user_visible_preview",sqlDisplayed:true,submittedUnchanged:false,additionalUserActionRequired:true,confirmationExists:false,resultsEnterChart:false,resultsEnterBA:false,persisted:false},{consumer:"Investigation.handleRunPreview -> executeBackendPreview",classification:"execution_candidate",sqlDisplayed:true,submittedUnchanged:true,additionalUserActionRequired:true,confirmationExists:false,resultsEnterChart:true,resultsEnterBA:true,persisted:false},{consumer:"backend-preview-executor -> local-duckdb-executor",classification:"direct_execution",sqlDisplayed:false,submittedUnchanged:true,additionalUserActionRequired:false,confirmationExists:false,resultsEnterChart:true,resultsEnterBA:true,persisted:false},{consumer:"DuckDB sandbox fallback",classification:"internal_preview_only",sqlDisplayed:false,submittedUnchanged:false,additionalUserActionRequired:false,confirmationExists:false,resultsEnterChart:true,resultsEnterBA:true,persisted:false}],conclusion:"Generated SQL is execution-capable on the local backend path; existence alone is not treated as execution.",productionBehaviorChanged:false});
 write("phase-5b3-aggregation-strategy-audit.json",{schemaVersion:"lightbi.phase-5b3-strategy-audit.v1",strategies,automaticSelection:null,implementedStrategy:null,productionBehaviorChanged:false});
 write("phase-5b3-migration-gate-audit.json",{schemaVersion:"lightbi.phase-5b3-migration-gate.v1",automaticSumConflictCoverageComplete:true,previewAuthorityTraceComplete:true,executionAuthorityTraceComplete:true,aggregationGuardShadowReplayComplete:true,guardStrategyDispositionComplete:true,criticalAggregationDivergencesResolved:false,aggregationProjectionPlanningEligible:true,authorityMigrationEvidenceSufficientForPhase5CPlanning:false,canonicalAuthorityMigrationEligible:false,finalWorktreeFullSuiteVerified:false,lossless:true,deterministic:true,blockerPreserving:true,importIsolated:true,productionWiring:{executed:false},phase5CStarted:false});
 write("phase-5b3-import-isolation-audit.json",{schemaVersion:"lightbi.phase-5b3-import-isolation-audit.v1",allowedImporters:["aggregation-guard-shadow.test.ts","aggregation-guard-shadow.corpus.test.ts"],productionImporters:[],barrelExported:false,persistence:false,telemetry:false,featureFlags:false,productionWiring:{executed:false}});
 expect(artifacts.every(x=>x.shadowOnly&&!x.planMutated&&!x.sqlChanged&&!x.approvalGranted&&!x.executionAuthorized)).toBe(true);expect(comparisonPolicyHash()).toBe("deb9a908b698792388b2d7b1fab853978a03087bcda37dc64682ab4d3e60f2c8");});});
