import {AGGREGATION_INTENT_ARTIFACT_VERSION,type AggregationIntentBoundaryArtifactV1,type AggregationIntentInputV1,type AggregationMigrationDispositionV1,type AggregationResultRestrictionV1,type ResultRestrictionCodeV1} from "./aggregation-intent-contracts";
import {EMPTY_REQUIRED_METRIC_EVIDENCE,aggregationIntentPolicyHash} from "./aggregation-intent-policy";

const restriction=(code:ResultRestrictionCodeV1,reason:string):AggregationResultRestrictionV1=>({code,reason});
export function evaluateAggregationIntentBoundary(input:AggregationIntentInputV1):AggregationIntentBoundaryArtifactV1{
 const c=input.canonical,i=input.intent,a=input.acknowledgement;let disposition:AggregationMigrationDispositionV1="physical_support_only";const restrictions:AggregationResultRestrictionV1[]=[];
 const add=(code:ResultRestrictionCodeV1,reason:string)=>{if(!restrictions.some(x=>x.code===code))restrictions.push(restriction(code,reason));};
 add("NOT_BUSINESS_VERIFIED","Phase 5B4 establishes no metric correctness.");add("NOT_ELIGIBLE_FOR_BA_CONCLUSION","Ungoverned aggregation cannot support a BA conclusion.");add("NOT_ELIGIBLE_FOR_NARRATIVE_CLAIM","Ungoverned aggregation cannot support narrative claims.");add("NOT_ELIGIBLE_FOR_AUTOMATIC_ALERT","Ungoverned aggregation cannot trigger alerts.");add("NOT_ELIGIBLE_FOR_PERSISTED_METRIC","Ungoverned aggregation cannot become a persisted metric.");
 if(!c.envelopeValid){disposition="invalid_canonical_envelope";add("REQUIRES_VALID_CANONICAL_ENVELOPE","Canonical envelope integrity is required.");}
 else if(!c.measurePresent||c.measureRole==="none"){disposition="no_measure_not_applicable";}
 else if(i.origin==="automatic_legacy_default"){disposition="automatic_default_prohibited";add("AUTOMATIC_AGGREGATION_PROHIBITED","Silent automatic aggregation is prohibited without governed semantics.");add("AUTOMATIC_COUNT_SUBSTITUTION_PROHIBITED","A blocked SUM cannot silently become COUNT.");}
 else if(i.origin==="explicit_user_selection"){disposition="exploratory_acknowledgement_required";add("EXPLORATORY_ONLY","Explicit calculations remain exploratory.");if(!a?.exploratoryExecutionConsent)add("REQUIRES_EXPLICIT_ACKNOWLEDGEMENT","Future exploratory execution requires explicit acknowledgement.");}
 else if(i.origin==="planner_recommendation"){disposition="planner_recommendation_only";add("EXPLORATORY_ONLY","A recommendation is neither selection nor execution.");}
 else if(i.origin==="imported_query_or_configuration"){disposition="imported_configuration_unverified";add("EXPLORATORY_ONLY","Imported configuration is explicit but not governed.");add("REQUIRES_EXPLICIT_ACKNOWLEDGEMENT","Future exploratory reuse requires acknowledgement.");}
 else if(i.origin==="governed_metric_contract"){disposition="governed_metric_evidence_required";add("REQUIRES_METRIC_DEFINITION","No approved governed metric exists in Phase 5B4.");}
 else if(i.origin==="unknown"){disposition="unknown_origin_blocked";add("REQUIRES_METRIC_DEFINITION","Aggregation authority cannot be inferred from its operator.");}
 if(c.measureRole==="unknown")add("REQUIRES_MEASURE_ROLE","Measure semantic role is unresolved.");
 if(c.grainState!=="confirmed")add("REQUIRES_GRAIN_CONFIRMATION","Source grain is unresolved.");
 if(c.repeatedParentRisk)add("REQUIRES_REPEATED_TOTAL_RULE","Repeated parent totals require governed handling.");
 if(c.snapshotRisk||c.measureRole==="balance")add("REQUIRES_SNAPSHOT_TIME_RULE","Snapshot measures require time aggregation rules.");
 if(["percentage","rate","average","unit_price"].includes(c.measureRole))add("REQUIRES_NON_ADDITIVE_FORMULA","Non-additive measures require a governed formula.");
 if(i.operator!=="NONE"&&i.origin!=="none"&&i.origin!=="planner_recommendation")add("REQUIRES_METRIC_DEFINITION","Business aggregation requires a governed metric definition.");
 if(i.operator==="COUNT"&&i.countSemantics==="count_distinct_values")add("REQUIRES_GOVERNED_KEY","Distinct count requires a governed key.");
 if(i.operator==="COUNT"&&i.countSemantics==="unknown_count_semantics")add("REQUIRES_MEASURE_ROLE","Count semantics are unresolved.");
 const authorityClasses=[input.physicalOperatorSupported?"physical_operator_supported" as const:i.origin==="unknown"?"unknown_origin" as const:"physical_operator_supported" as const,...(i.origin==="automatic_legacy_default"?["automatic_default_aggregation" as const]:i.origin==="explicit_user_selection"?[i.operator==="COUNT"&&i.countSemantics==="count_rows"?"descriptive_row_count" as const:"explicit_exploratory_aggregation" as const]:i.origin==="planner_recommendation"?["planner_recommendation" as const]:i.origin==="governed_metric_contract"?["governed_metric_aggregation" as const]:i.origin==="unknown"?["unknown_origin" as const]:[])];
 return{schemaVersion:AGGREGATION_INTENT_ARTIFACT_VERSION,identity:structuredClone(input.identity),policyVersion:"lightbi.aggregation-intent-policy.v1",policyHash:aggregationIntentPolicyHash(),intent:structuredClone(i),authorityClasses:[...new Set(authorityClasses)],exploratoryBoundary:{userIntentKnown:i.origin==="explicit_user_selection"||i.origin==="imported_query_or_configuration",exploratoryExecutionConsent:a?.exploratoryExecutionConsent===true,businessCorrectnessEstablished:false,acknowledgement:a?structuredClone(a):null,candidateForFutureExploratoryExecution:i.origin==="explicit_user_selection"&&a?.exploratoryExecutionConsent===true},decisionUseBoundary:{chartDisplayEligible:false,BAConclusionEligible:false,narrativeClaimEligible:false,automaticAlertEligible:false,persistedMetricEligible:false,executionAuthorized:false},disposition,restrictions,requiredMetricEvidence:input.metricEvidence?structuredClone(input.metricEvidence):EMPTY_REQUIRED_METRIC_EVIDENCE(),debt:restrictions.map(x=>({code:x.code,severity:x.code.startsWith("NOT_")?"material" as const:"critical" as const,blocksAuthorityMigration:true as const})),rawInputPreserved:true,planMutated:false,sqlChanged:false,canonicalStateChanged:false,operationApproval:{executed:false},metricExecution:{executed:false},domainActivation:{executed:false},canonicalAuthorityMigrationEligible:false,productionWiring:{executed:false}};
}
