import type {CapabilityReadinessStateV1} from "./readiness-contracts";

export const AGGREGATION_GUARD_SHADOW_VERSION="lightbi.aggregation-guard-shadow.v1" as const;
export const AGGREGATION_GUARD_POLICY_VERSION="lightbi.aggregation-guard-shadow-policy.v1" as const;
export type AggregationOriginV1="automatic_default"|"explicit_user"|"planner_recommendation"|"governed_metric"|"none"|"unknown";
export type AggregationOperatorV1="SUM"|"AVG"|"COUNT"|"NONE"|"UNKNOWN";
export type AggregationGuardDispositionV1="observe_only_no_conflict"|"automatic_sum_would_be_blocked"|"explicit_aggregation_requires_confirmation"|"metric_semantics_required"|"grain_confirmation_required"|"repeated_total_protection_required"|"snapshot_time_rule_required"|"non_additive_measure_rule_required"|"no_measure_not_applicable"|"physical_operator_only"|"unsupported_or_unknown"|"invalid_canonical_envelope";
export type AggregationGuardEvidenceCodeV1="REQUIRE_MEASURE_ROLE"|"REQUIRE_GRAIN_CONFIRMATION"|"REQUIRE_METRIC_DEFINITION"|"REQUIRE_AGGREGATION_RULE"|"REQUIRE_REPEATED_TOTAL_HANDLING"|"REQUIRE_SNAPSHOT_TIME_RULE"|"REQUIRE_NON_ADDITIVE_FORMULA"|"REQUIRE_EXPLICIT_USER_CONFIRMATION"|"REQUIRE_DOMAIN_METRIC_PACK"|"REQUIRE_VALID_CANONICAL_ENVELOPE";
export type PreviewExecutionAuthorityV1="internal_preview_only"|"user_visible_preview"|"reusable_query_plan"|"execution_candidate"|"direct_execution"|"authority_unknown";
export type LegacyAggregationIntentV1={operator:AggregationOperatorV1;origin:AggregationOriginV1;explicit:boolean;automaticallyDefaulted:boolean};
export type CanonicalAggregationRestrictionV1={envelopeValid:boolean;capabilityStates:Partial<Record<"measure_role_assessment_ready"|"descriptive_counting_ready"|"dimensional_grouping_ready"|"numeric_aggregation_ready"|"repeated_measure_protection_ready"|"snapshot_time_aggregation_ready",CapabilityReadinessStateV1>>;measurePresent:boolean;measureRole:"additive"|"percentage"|"rate"|"average"|"unit_price"|"balance"|"unknown"|"none";grainState:"confirmed"|"ambiguous"|"unknown";repeatedParentRisk:boolean;snapshotRisk:boolean;limitations:string[];risks:string[]};
export type AggregationGuardInputV1={sourceIdentity:string;sourceHash:{algorithm:"sha256";value:string};physicalColumnIndex:number;physicalColumn:string;legacyNumericHealth:Record<string,unknown>|null;intent:LegacyAggregationIntentV1;canonical:CanonicalAggregationRestrictionV1;authority:PreviewExecutionAuthorityV1;legacyPlan?:unknown;legacySql?:string|null};
export type AggregationGuardReasonV1={code:string;message:string};
export type AggregationGuardRequiredEvidenceV1={code:AggregationGuardEvidenceCodeV1;present:false};
export type AggregationGuardMigrationImpactV1={canonicalAuthorityMigrationEligible:false;productionWiring:{executed:false}};
export type AggregationGuardShadowArtifactV1={schemaVersion:typeof AGGREGATION_GUARD_SHADOW_VERSION;identity:{sourceIdentity:string;sourceHash:{algorithm:"sha256";value:string};physicalColumnIndex:number;physicalColumn:string};legacyNumericHealth:Record<string,unknown>|null;incomingIntent:LegacyAggregationIntentV1;canonicalRestriction:CanonicalAggregationRestrictionV1;disposition:AggregationGuardDispositionV1;reasons:AggregationGuardReasonV1[];requiredEvidence:AggregationGuardRequiredEvidenceV1[];authority:PreviewExecutionAuthorityV1;existingLegacyOutputPreserved:true;shadowOnly:true;planMutated:false;sqlChanged:false;approvalGranted:false;executionAuthorized:false;migrationImpact:AggregationGuardMigrationImpactV1};
export type AggregationGuardPolicyV1={schemaVersion:typeof AGGREGATION_GUARD_POLICY_VERSION;precedence:AggregationGuardDispositionV1[];forbiddenEffects:string[]};
