import { deterministicPolicySha256 } from "./contextual-evidence-policy";
import type { QuestionActionPolicyV1 } from "./governed-question-action-contracts";

const commonProhibitedUses = [
  "runtime_execution",
  "sql_generation",
  "decision_authorization",
  "forecasting",
] as const;

export const COMMERCE_DISTRIBUTION_QUESTION_POLICY_V1 = {
  schemaVersion: "lightbi.question-action-policy.v1",
  contractVersion: "lightbi.governed-question-action-contract.v1",
  domainPackId: "commerce_distribution_mvp",
  maxDefaultQuestions: 5,
  statePreference: ["ready", "conditionally_ready", "blocked", "unknown", "unsupported", "not_applicable"],
  questionFamilies: [
    { questionId: "commerce.sales_revenue.over_time", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue"], metricId: "sales_revenue", title: "How is sales revenue changing over time?", businessPurpose: "Review governed sales revenue across a compatible event or reporting-period basis.", intent: "trend", actionKind: "trend_candidate", requiredDimensionGroups: [["report_date", "time_period"]], timeRequirement: "event_or_period", sourceComplexity: "source_local", priority: 10, prohibitedUses: [...commonProhibitedUses, "currency_conversion"] },
    { questionId: "commerce.sales_revenue.by_product", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue"], metricId: "sales_revenue", title: "Which products contribute the most sales revenue?", businessPurpose: "Rank governed sales revenue by a compatible product or SKU dimension.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["product", "sku"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 20, prohibitedUses: [...commonProhibitedUses, "profitability_claim"] },
    { questionId: "commerce.sales_revenue.by_warehouse", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue"], metricId: "sales_revenue", title: "Which stores or warehouses contribute the most sales revenue?", businessPurpose: "Rank governed sales revenue by the resolved store or warehouse dimension.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["warehouse"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 21, prohibitedUses: [...commonProhibitedUses, "profitability_claim"] },
    { questionId: "commerce.sales_revenue.by_category", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue"], metricId: "sales_revenue", title: "Which product categories contribute the most sales revenue?", businessPurpose: "Rank governed sales revenue by a canonically resolved product category.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["category"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 41, prohibitedUses: [...commonProhibitedUses, "profitability_claim"] },
    { questionId: "commerce.sales_revenue.by_salesperson", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue", "performance"], metricId: "sales_revenue", title: "Which salespeople contribute the most sales revenue?", businessPurpose: "Rank governed sales revenue by a canonically resolved salesperson without inferring individual causality.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["salesperson"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 42, prohibitedUses: [...commonProhibitedUses, "employee_causality_claim", "profitability_claim"] },
    { questionId: "commerce.sales_revenue.by_payment_method", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue"], metricId: "sales_revenue", title: "How is sales revenue distributed by payment method?", businessPurpose: "Describe governed sales revenue by a canonically resolved payment method without claiming channel causality.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["payment_method"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 43, prohibitedUses: [...commonProhibitedUses, "payment_channel_causality_claim", "profitability_claim"] },
    { questionId: "commerce.quantity_sold.over_time", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue"], metricId: "quantity_sold", title: "How is quantity sold changing over time?", businessPurpose: "Review governed sold quantity across a compatible event or reporting-period basis.", intent: "trend", actionKind: "trend_candidate", requiredDimensionGroups: [["report_date", "time_period"]], timeRequirement: "event_or_period", sourceComplexity: "source_local", priority: 30, prohibitedUses: [...commonProhibitedUses, "inventory_movement_claim", "unit_conversion"] },
    { questionId: "commerce.quantity_sold.by_product", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue"], metricId: "quantity_sold", title: "Which products account for the most quantity sold?", businessPurpose: "Rank governed sold quantity by a compatible product or SKU dimension.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["product", "sku"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 40, prohibitedUses: [...commonProhibitedUses, "inventory_balance_claim", "unit_conversion"] },
    { questionId: "commerce.transaction_count.summary", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["revenue"], metricId: "transaction_count", title: "How many governed commercial transactions are present?", businessPurpose: "Count governed commercial transaction identities without relabeling arbitrary rows as transactions.", intent: "summary", actionKind: "count_candidate", requiredDimensionGroups: [], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 50, prohibitedUses: [...commonProhibitedUses, "row_count_as_transaction_count", "implicit_count_distinct"] },
    { questionId: "commerce.inventory_on_hand.as_of", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["inventory"], metricId: "inventory_on_hand", title: "What inventory is on hand at the available as-of basis?", businessPurpose: "Review a governed point-in-time inventory balance without treating snapshots as movement.", intent: "point_in_time", actionKind: "snapshot_candidate", requiredDimensionGroups: [], timeRequirement: "point_in_time_as_of", sourceComplexity: "source_local", priority: 60, prohibitedUses: [...commonProhibitedUses, "inventory_movement_claim", "sum_across_time", "unit_conversion"] },
    { questionId: "commerce.inventory_on_hand.by_product", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["inventory"], metricId: "inventory_on_hand", title: "Which items hold the most inventory at the as-of basis?", businessPurpose: "Rank a governed point-in-time inventory balance by its bound item identity.", intent: "ranking", actionKind: "snapshot_candidate", requiredDimensionGroups: [["sku"]], timeRequirement: "point_in_time_as_of", sourceComplexity: "source_local", priority: 65, prohibitedUses: [...commonProhibitedUses, "inventory_movement_claim", "sum_across_time", "unit_conversion"] },
    { questionId: "commerce.inventory_on_hand.by_warehouse", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["inventory"], metricId: "inventory_on_hand", title: "Which warehouses hold the most inventory at the as-of basis?", businessPurpose: "Rank a governed point-in-time inventory balance by its bound warehouse identity.", intent: "ranking", actionKind: "snapshot_candidate", requiredDimensionGroups: [["warehouse"]], timeRequirement: "point_in_time_as_of", sourceComplexity: "source_local", priority: 66, prohibitedUses: [...commonProhibitedUses, "inventory_movement_claim", "sum_across_time", "unit_conversion"] },
    { questionId: "commerce.inventory_on_hand.by_item_warehouse", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["inventory"], metricId: "inventory_on_hand", title: "What is the inventory balance for each item and warehouse at the as-of basis?", businessPurpose: "Verify governed point-in-time inventory at its exact item and warehouse identity grain.", intent: "ranking", actionKind: "snapshot_candidate", requiredDimensionGroups: [["sku"], ["warehouse"]], timeRequirement: "point_in_time_as_of", sourceComplexity: "source_local", priority: 67, prohibitedUses: [...commonProhibitedUses, "inventory_movement_claim", "sum_across_time", "unit_conversion"] },
    { questionId: "commerce.delivery_count.summary", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["operations"], metricId: "delivery_count", title: "How many governed deliveries are present?", businessPurpose: "Count governed delivery identities without relabeling status rows or line rows as deliveries.", intent: "summary", actionKind: "count_candidate", requiredDimensionGroups: [], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 70, prohibitedUses: [...commonProhibitedUses, "row_count_as_delivery_count", "implicit_count_distinct"] },
    { questionId: "commerce.delivery_count.by_status", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["operations"], metricId: "delivery_count", title: "How are governed deliveries distributed by status?", businessPurpose: "Break down governed delivery identities by a canonically resolved delivery status.", intent: "status_breakdown", actionKind: "status_breakdown_candidate", requiredDimensionGroups: [["delivery_status"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 75, prohibitedUses: [...commonProhibitedUses, "status_row_count_as_delivery_count"] },
    { questionId: "inventory.shipment_count.by_current_location", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["inventory"], metricId: "delivery_count", title: "How are governed shipments distributed by current location?", businessPurpose: "Describe governed shipment identities by their canonically resolved current location without claiming an item-level on-hand balance.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["current_location"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 72, prohibitedUses: [...commonProhibitedUses, "inventory_on_hand_claim", "row_count_as_shipment_count"] },
    { questionId: "inventory.shipment_count.by_service_group", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["inventory"], metricId: "delivery_count", title: "How are governed shipments distributed by service group?", businessPurpose: "Compare governed shipment identities across the canonically resolved logistics service group.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["service_group"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 73, prohibitedUses: [...commonProhibitedUses, "inventory_on_hand_claim", "service_quality_causality_claim"] },
    { questionId: "inventory.shipment_count.by_load_status", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["inventory"], metricId: "delivery_count", title: "How are governed shipments distributed by load status?", businessPurpose: "Break down governed shipment identities by the canonically resolved load status.", intent: "status_breakdown", actionKind: "status_breakdown_candidate", requiredDimensionGroups: [["load_status"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 74, prohibitedUses: [...commonProhibitedUses, "inventory_on_hand_claim", "status_row_count_as_shipment_count"] },
    { questionId: "inventory.shipment_count.by_stock_age", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["inventory"], metricId: "delivery_count", title: "How are governed shipments distributed by stock age?", businessPurpose: "Describe governed shipment identities across canonically resolved stock-age values without inferring aging thresholds or causes.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["stock_age"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 75, prohibitedUses: [...commonProhibitedUses, "inventory_on_hand_claim", "aging_threshold_inference", "delay_causality_claim"] },
    { questionId: "operations.trip_count.summary", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["operations"], metricId: "trip_count", title: "How many governed trips are present?", businessPurpose: "Count source-bound, user-confirmed trip identities without relabeling operational rows as trips.", intent: "summary", actionKind: "count_candidate", requiredDimensionGroups: [], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 76, prohibitedUses: [...commonProhibitedUses, "row_count_as_trip_count", "unconfirmed_count_distinct"] },
    { questionId: "operations.trip_count.by_route", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["operations"], metricId: "trip_count", title: "Which routes carry the most governed trips?", businessPurpose: "Compare confirmed trip identities by canonically resolved route.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["route"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 77, prohibitedUses: [...commonProhibitedUses, "row_count_as_trip_count"] },
    { questionId: "operations.trip_count.by_driver", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["operations"], metricId: "trip_count", title: "How are governed trips distributed by driver?", businessPurpose: "Compare confirmed trip identities by canonically resolved driver.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["driver"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 78, prohibitedUses: [...commonProhibitedUses, "driver_performance_claim_without_outcome"] },
    { questionId: "operations.trip_count.by_on_time_status", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["operations", "performance"], metricId: "trip_count", title: "How are governed trips distributed by on-time status?", businessPurpose: "Break down confirmed trip identities by canonically resolved on-time status.", intent: "status_breakdown", actionKind: "status_breakdown_candidate", requiredDimensionGroups: [["on_time_status"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 79, prohibitedUses: [...commonProhibitedUses, "row_count_as_trip_count", "sla_causality_claim"] },
    { questionId: "performance.average_quality_score.summary", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["performance"], metricId: "average_quality_score", title: "What is the governed average quality score?", businessPurpose: "Summarize the arithmetic mean of the canonically resolved quality score across independently identified evaluated entities.", intent: "summary", actionKind: "summary_candidate", requiredDimensionGroups: [], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 81, prohibitedUses: [...commonProhibitedUses, "sum_of_scores_as_average", "employee_causality_claim", "appraisal_validity_claim"] },
    { questionId: "performance.average_quality_score.by_rank", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["performance"], metricId: "average_quality_score", title: "How does quality score vary by performance rank?", businessPurpose: "Compare the governed quality-score average across the canonically resolved ordinal performance rank.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["performance_rank"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 82, prohibitedUses: [...commonProhibitedUses, "rank_causality_claim", "appraisal_validity_claim"] },
    { questionId: "descriptive.source_records.by_team", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["performance"], metricId: "source_record_count", title: "How are source records distributed by team or group?", businessPurpose: "Describe physical source-record volume by the canonically resolved team or group without claiming a distinct participant count.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["team"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 83, prohibitedUses: [...commonProhibitedUses, "source_rows_as_people", "source_rows_as_events", "distinct_participant_claim"] },
    { questionId: "descriptive.source_records.by_role", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["performance"], metricId: "source_record_count", title: "How are source records distributed by role or position?", businessPurpose: "Describe physical source-record volume by the canonically resolved role or position without claiming headcount.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["role"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 84, prohibitedUses: [...commonProhibitedUses, "source_rows_as_people", "headcount_claim", "performance_claim"] },
    { questionId: "descriptive.source_records.by_person", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["performance"], metricId: "source_record_count", title: "How are source records distributed by person or participant?", businessPurpose: "Describe physical source-record frequency by the canonically resolved person or participant without treating frequency as performance.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["person"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 85, prohibitedUses: [...commonProhibitedUses, "source_rows_as_people", "participant_performance_claim", "causality_claim"] },
    { questionId: "descriptive.source_records.by_coach", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["performance"], metricId: "source_record_count", title: "How are source records distributed by coach or lead?", businessPurpose: "Describe physical source-record frequency by the canonically resolved coach or lead without inferring coaching quality.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["coach"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 86, prohibitedUses: [...commonProhibitedUses, "source_rows_as_people", "coach_quality_claim", "causality_claim"] },
    { questionId: "descriptive.source_records.by_previous_outcome", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["customer", "performance"], metricId: "source_record_count", title: "How are source records distributed by previous campaign outcome?", businessPurpose: "Describe physical source-record volume by the canonically resolved previous outcome without claiming conversion, response rate, or causality.", intent: "status_breakdown", actionKind: "status_breakdown_candidate", requiredDimensionGroups: [["previous_outcome"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 87, prohibitedUses: [...commonProhibitedUses, "source_rows_as_customers", "conversion_rate_claim", "campaign_causality_claim"] },
    { questionId: "descriptive.source_records.by_segment", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["customer"], metricId: "source_record_count", title: "How are source records distributed by customer segment?", businessPurpose: "Describe physical source-record volume by the canonically resolved segment without claiming distinct-customer population.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["segment"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 88, prohibitedUses: [...commonProhibitedUses, "source_rows_as_customers", "population_share_claim"] },
    { questionId: "descriptive.source_records.by_contact", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["customer"], metricId: "source_record_count", title: "How are source records distributed by contact?", businessPurpose: "Describe physical source-record volume by the canonically resolved contact field without claiming channel effectiveness.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["contact"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 89, prohibitedUses: [...commonProhibitedUses, "source_rows_as_customers", "channel_effectiveness_claim", "campaign_causality_claim"] },
    { questionId: "descriptive.source_records.by_campaign", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["customer", "performance"], metricId: "source_record_count", title: "How are source records distributed by campaign?", businessPurpose: "Describe physical source-record volume by the canonically resolved campaign without claiming campaign success.", intent: "ranking", actionKind: "ranking_candidate", requiredDimensionGroups: [["campaign"]], timeRequirement: "not_required", sourceComplexity: "source_local", priority: 90, prohibitedUses: [...commonProhibitedUses, "source_rows_as_customers", "campaign_success_claim", "campaign_causality_claim"] },
    { questionId: "commerce.gross_profit.over_time", version: "1.0.0", domainPackId: "commerce_distribution_mvp", businessPerspectiveIds: ["finance"], metricId: "gross_profit", title: "How is governed gross profit changing over compatible periods?", businessPurpose: "Review revenue less compatible cost only when the governed gross-profit preflight permits the derivation.", intent: "trend", actionKind: "trend_candidate", requiredDimensionGroups: [["report_date", "time_period"]], timeRequirement: "compatible_period", sourceComplexity: "relationship_dependent", priority: 80, prohibitedUses: [...commonProhibitedUses, "margin_claim", "unreconciled_revenue_cost_subtraction", "currency_conversion"] },
  ],
  rules: [
    { ruleId: "question.metric_only.v1", description: "A question requires a governed Phase 5M1 metric definition and its exact preflight result." },
    { ruleId: "question.no_state_strengthening.v1", description: "Question and action states may preserve or weaken, never strengthen, metric preflight state." },
    { ruleId: "question.canonical_dimensions_only.v1", description: "Required dimensions must be probable or confirmed selected canonical resolutions." },
    { ruleId: "question.blocked_not_default.v1", description: "Blocked, unknown, unsupported, and not-applicable questions are explanation-only." },
    { ruleId: "question.rank_deterministic.v1", description: "Rank by metric state, source complexity, policy priority, and governed identity." },
    { ruleId: "action.candidate_only.v1", description: "Phase 5M2 may describe guarded action candidates but cannot create, authorize, or execute runtime actions." },
  ],
  forbiddenInference: [
    "legacy_playbook_establishes_question",
    "alias_only_establishes_question",
    "filename_or_sample_id_changes_question",
    "blocked_metric_advertised_as_default",
    "unit_price_is_revenue",
    "snapshot_is_inventory_movement",
    "row_count_is_governed_entity_count",
    "source_record_count_is_distinct_entity_count",
    "missing_time_basis_is_trend",
    "gross_profit_without_compatible_cost",
    "question_authorizes_execution",
  ],
} as const satisfies QuestionActionPolicyV1;

export function questionActionPolicyHash(value: unknown = COMMERCE_DISTRIBUTION_QUESTION_POLICY_V1): string {
  return deterministicPolicySha256(value);
}
