import { deterministicPolicySha256 } from "./contextual-evidence-policy";
import type { GovernedMetricDefinitionV1, GovernedMetricPolicyV1 } from "./governed-domain-metric-contracts";

const base = {
  schemaVersion: "lightbi.governed-domain-metric-contract.v1",
  domainPackId: "commerce_distribution_mvp",
  version: "1.0.0",
  groupingDimensions: ["product", "sku", "customer", "warehouse", "report_date", "time_period"],
  requiredRelationships: [],
  prohibitedEvidenceStates: ["ambiguous", "unknown", "technical", "unsupported_input"],
  provenance: ["contract", "synthetic", "golden_tuning"],
  approvalState: "governed_definition",
  executionAuthorization: false,
} as const;

export const GOVERNED_METRIC_DEFINITIONS_V1 = [
  {
    ...base,
    metricId: "sales_revenue",
    businessName: "Sales revenue",
    semanticMeaning: "Revenue earned from compatible commercial transaction or line records.",
    measureRole: "flow_amount",
    aggregationOperator: "sum",
    requirements: [{ requirementId: "revenue_amount", semanticSignals: ["revenue", "net_revenue", "invoice_total"], semanticMode: "any", allowedSemanticStates: ["confirmed", "probable"], allowedStructuralForms: ["line", "document", "entity"], minimumGrainState: "probable", allowedTemporalModes: ["event", "reporting_period", "effective_time"], requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "measure_role_assessment_ready", "repeated_measure_protection_ready"], relationshipRequired: false }],
    timeBehavior: "transaction_flow",
    additivity: "additive",
    duplicateHandling: "Duplicate physical rows or identities block until governed handling is proven.",
    repeatedParentHandling: "Repeated document totals across line rows block summation.",
    snapshotHandling: "Snapshot and balance values are prohibited.",
    nullHandling: "Null values are excluded only after the source profile reports them.",
    unitBehavior: "Unit prices, percentages, and rates are not revenue.",
    currencyBehavior: "An explicit compatible currency basis is required for ready; absence remains conditional.",
    requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "measure_role_assessment_ready", "repeated_measure_protection_ready"],
    outputType: "amount",
    limitations: ["No currency conversion is performed.", "No metric execution occurs in Phase 5M1."],
  },
  {
    ...base,
    metricId: "quantity_sold",
    businessName: "Quantity sold",
    semanticMeaning: "Sold units represented by compatible transaction, line, or event records.",
    measureRole: "flow_quantity",
    aggregationOperator: "sum",
    requirements: [{ requirementId: "sold_quantity", semanticSignals: ["sold_qty", "quantity"], semanticMode: "any", allowedSemanticStates: ["confirmed", "probable"], allowedStructuralForms: ["line", "document", "entity"], minimumGrainState: "probable", allowedTemporalModes: ["event", "reporting_period", "effective_time"], requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "measure_role_assessment_ready"], relationshipRequired: false }],
    timeBehavior: "transaction_flow",
    additivity: "additive",
    duplicateHandling: "Duplicate line or parent totals block summation.",
    repeatedParentHandling: "Repeated parent quantities block until resolved.",
    snapshotHandling: "Inventory snapshots cannot satisfy quantity sold.",
    nullHandling: "Null values are excluded only after profiling evidence.",
    unitBehavior: "An explicit compatible unit basis is required for ready; absence remains conditional.",
    currencyBehavior: "Not applicable.",
    requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "measure_role_assessment_ready"],
    outputType: "quantity",
    limitations: ["No unit conversion is performed.", "No metric execution occurs in Phase 5M1."],
  },
  {
    ...base,
    metricId: "transaction_count",
    businessName: "Transaction count",
    semanticMeaning: "Count of governed commercial transaction identities, not arbitrary rows or customers.",
    measureRole: "entity_count",
    aggregationOperator: "count_governed_identity",
    requirements: [{ requirementId: "transaction_identity", semanticSignals: ["order", "sales_order", "billing_document"], semanticMode: "any", allowedSemanticStates: ["confirmed", "probable"], allowedStructuralForms: ["document", "line", "entity"], minimumGrainState: "probable", allowedTemporalModes: ["event", "reporting_period", "effective_time", "none"], requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "row_identity_ready", "descriptive_counting_ready"], relationshipRequired: false }],
    timeBehavior: "transaction_flow",
    additivity: "descriptive_count_only",
    duplicateHandling: "A governed unique identity is mandatory; COUNT DISTINCT is never inferred.",
    repeatedParentHandling: "Line rows require a confirmed or probable parent transaction identity.",
    snapshotHandling: "Not applicable.",
    nullHandling: "Null transaction identities block the governed count.",
    unitBehavior: "Not applicable.",
    currencyBehavior: "Not applicable.",
    requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "row_identity_ready", "descriptive_counting_ready"],
    outputType: "count",
    limitations: ["Row count is not silently relabeled as transaction count."],
  },
  {
    ...base,
    metricId: "inventory_on_hand",
    businessName: "Inventory on hand",
    semanticMeaning: "Stock quantity at one compatible point-in-time basis.",
    measureRole: "snapshot_balance",
    aggregationOperator: "sum",
    requirements: [{ requirementId: "inventory_snapshot_quantity", semanticSignals: ["inventory", "stock_qty"], semanticMode: "any", allowedSemanticStates: ["confirmed", "probable"], allowedStructuralForms: ["entity", "aggregate"], minimumGrainState: "probable", allowedTemporalModes: ["snapshot", "effective_time"], requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "temporal_analysis_ready", "measure_role_assessment_ready"], relationshipRequired: false }],
    timeBehavior: "point_in_time_snapshot",
    additivity: "semi_additive",
    duplicateHandling: "Duplicate item-location-snapshot identities block aggregation.",
    repeatedParentHandling: "Repeated balances block until one snapshot identity is selected.",
    snapshotHandling: "May aggregate compatible products and locations only at one as-of basis; never across time.",
    nullHandling: "Null snapshot quantities remain explicit and are not imputed.",
    unitBehavior: "Compatible unit basis is required for ready; absence remains conditional.",
    currencyBehavior: "Not applicable.",
    requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "temporal_analysis_ready", "measure_role_assessment_ready"],
    outputType: "quantity",
    limitations: ["No inventory movement is inferred from snapshots."],
  },
  {
    ...base,
    metricId: "delivery_count",
    businessName: "Delivery count",
    semanticMeaning: "Count of governed delivery or shipment identities.",
    measureRole: "entity_count",
    aggregationOperator: "count_governed_identity",
    requirements: [{ requirementId: "delivery_identity", semanticSignals: ["shipment"], semanticMode: "any", allowedSemanticStates: ["confirmed", "probable"], allowedStructuralForms: ["document", "entity", "line"], minimumGrainState: "probable", allowedTemporalModes: ["event", "reporting_period", "effective_time", "none"], requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "row_identity_ready", "descriptive_counting_ready"], relationshipRequired: false }],
    timeBehavior: "transaction_flow",
    additivity: "descriptive_count_only",
    duplicateHandling: "A governed delivery identity is mandatory.",
    repeatedParentHandling: "Delivery lines are not deliveries; a parent identity is required.",
    snapshotHandling: "Not applicable.",
    nullHandling: "Null delivery identities block the governed count.",
    unitBehavior: "Not applicable.",
    currencyBehavior: "Not applicable.",
    requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "row_identity_ready", "descriptive_counting_ready"],
    outputType: "count",
    limitations: ["Status row count is not silently relabeled as delivery count."],
  },
  {
    ...base,
    metricId: "gross_profit",
    businessName: "Gross profit",
    semanticMeaning: "Governed compatible revenue less governed compatible cost.",
    measureRole: "derived_amount",
    aggregationOperator: "derive_subtraction",
    requirements: [
      { requirementId: "gross_profit_revenue", semanticSignals: ["revenue", "net_revenue", "invoice_total"], semanticMode: "any", allowedSemanticStates: ["confirmed", "probable"], allowedStructuralForms: ["line", "document", "entity"], minimumGrainState: "probable", allowedTemporalModes: ["event", "reporting_period", "effective_time"], requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "measure_role_assessment_ready"], relationshipRequired: false },
      { requirementId: "gross_profit_cost", semanticSignals: ["cost", "total_cost"], semanticMode: "any", allowedSemanticStates: ["confirmed", "probable"], allowedStructuralForms: ["line", "document", "entity"], minimumGrainState: "probable", allowedTemporalModes: ["event", "reporting_period", "effective_time"], requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "measure_role_assessment_ready"], relationshipRequired: false },
    ],
    timeBehavior: "period_flow",
    additivity: "additive",
    duplicateHandling: "Revenue and cost duplicate handling must both be governed.",
    repeatedParentHandling: "Repeated totals on either component block derivation.",
    snapshotHandling: "Snapshot balances cannot satisfy either component.",
    nullHandling: "Missing cost or revenue blocks derivation; no zero imputation.",
    unitBehavior: "Revenue and cost must share a compatible monetary basis.",
    currencyBehavior: "Revenue and cost currency and time basis must be compatible; no conversion is inferred.",
    requiredReadinessCapabilities: ["physical_profile_ready", "semantic_labeling_ready", "grain_interpretation_ready", "measure_role_assessment_ready", "repeated_measure_protection_ready"],
    outputType: "amount",
    limitations: ["Cross-source derivation requires a governed relationship and remains blocked in Phase 5M1."],
  },
] as const satisfies readonly GovernedMetricDefinitionV1[];

export const GOVERNED_METRIC_POLICY_V1 = {
  schemaVersion: "lightbi.governed-metric-policy.v1",
  contractVersion: "lightbi.governed-domain-metric-contract.v1",
  domainPackId: "commerce_distribution_mvp",
  metricOrder: GOVERNED_METRIC_DEFINITIONS_V1.map((metric) => metric.metricId),
  rules: [
    { ruleId: "metric.semantic_specific.v1", description: "Only probable or confirmed canonical semantic resolution can satisfy a metric requirement." },
    { ruleId: "metric.grain_specific.v1", description: "Every metric must independently prove a compatible grain and temporal mode." },
    { ruleId: "metric.no_global_additivity.v1", description: "Metric readiness never changes canonical safeToAggregate=false." },
    { ruleId: "metric.repeated_parent_blocks.v1", description: "Repeated parent values or mixed aggregation block affected sum metrics." },
    { ruleId: "metric.snapshot_time.v1", description: "Snapshot balances are semi-additive and cannot be summed across time." },
    { ruleId: "metric.identity_count.v1", description: "Entity counts require a governed key; no implicit COUNT DISTINCT is allowed." },
    { ruleId: "metric.relationship_fail_closed.v1", description: "Cross-source metrics require governed relationship compatibility." },
    { ruleId: "metric.runtime_isolated.v1", description: "Preflight cannot create or authorize runtime actions or results." },
  ],
  forbiddenInference: [
    "header_alias_alone_establishes_metric",
    "numeric_parse_establishes_measure",
    "unit_price_is_revenue",
    "rate_or_percentage_is_additive",
    "balance_is_period_flow",
    "unknown_risk_means_safe",
    "filename_or_sample_id_changes_policy",
    "evaluation_only_case_tunes_policy",
  ],
} as const satisfies GovernedMetricPolicyV1;

export function governedMetricPolicyHash(value: unknown = GOVERNED_METRIC_POLICY_V1): string {
  return deterministicPolicySha256(value);
}
