import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {describe,expect,it} from "vitest";
import * as XLSX from "xlsx";
import {aggregateContextualEvidence} from "./contextual-evidence-aggregator";
import type {CandidateAbsenceDebtV1} from "./contextual-evidence-contracts";
import {generateGrainCandidateArtifact} from "./grain-candidate-engine";
import {grainCandidatePolicyHash,GRAIN_CANDIDATE_POLICY} from "./grain-candidate-policy";
import {profilePhysicalSource} from "./profiler";
import {generateSemanticCandidateArtifact} from "./semantic-candidate-engine";
import {resolveSemanticShadow} from "./semantic-resolver";

const ROOT=path.resolve(__dirname,"../../../../..");
type Group="golden"|"holdout"|"adversarial"|"multi_file";
type Source={path:string;sheet:string;sha256:string};
type GrainTruth={candidateKeys:string[][];parentKeys:string[][];measureExpectations:Array<{physicalColumn:string;additiveAcrossRows:boolean;repeatedWithinParent:boolean}>};
type Sample={id:string;group:Group;provenance:{tuningUse:"allowed"|"forbidden"};sources:Source[];dataset:{grainTruth:GrainTruth};recognition:{requiredMappings:Array<{physicalColumn:string;canonicalSignal:string}>;expectedAmbiguousMappings:Array<{physicalColumn:string;candidateSignals:string[]}>}};
const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,"sample-corpus/versions/1.4.0/manifest.json"),"utf8")) as {corpusVersion:string;groundTruthFiles:Array<{path:string}>};
const samples=manifest.groundTruthFiles.flatMap((entry)=>(JSON.parse(fs.readFileSync(path.join(ROOT,entry.path),"utf8")) as {samples:Sample[]}).samples);
function load(source:Source){const key=`${source.path}#${source.sheet}`,bytes=fs.readFileSync(path.join(ROOT,source.path));expect(crypto.createHash("sha256").update(bytes).digest("hex")).toBe(source.sha256);const workbook=XLSX.read(bytes,{raw:true}),sheet=workbook.Sheets[source.sheet]??workbook.Sheets[workbook.SheetNames[0]];if(!sheet)throw new Error(`missing sheet ${key}`);const rawRows=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:"",blankrows:true}),physical=profilePhysicalSource({schemaVersion:"lightbi.physical-source-input.v1",source:{sourceId:key,kind:"local_file",label:path.basename(source.path),hash:{algorithm:"sha256",value:source.sha256}},rawRows}),candidate=generateSemanticCandidateArtifact(physical);return{key,rawRows,physical,candidate};}
function debt(sample:Sample,all:ReturnType<typeof load>[]):CandidateAbsenceDebtV1[]{const ids=(column:string)=>new Set(all.flatMap(({candidate})=>candidate.observations.filter((item)=>item.physicalColumn===column).flatMap((item)=>item.candidateSet.candidates.map((candidate)=>candidate.candidateId))));const result:CandidateAbsenceDebtV1[]=[];sample.recognition.requiredMappings.forEach((mapping)=>{if(!ids(mapping.physicalColumn).has(mapping.canonicalSignal))result.push({physicalColumn:`${sample.id}:${mapping.physicalColumn}`,candidateId:mapping.canonicalSignal,reasonCode:"required_candidate_absent"});});sample.recognition.expectedAmbiguousMappings.forEach((mapping)=>mapping.candidateSignals.forEach((candidateId)=>{if(!ids(mapping.physicalColumn).has(candidateId))result.push({physicalColumn:`${sample.id}:${mapping.physicalColumn}`,candidateId,reasonCode:"contextual_candidate_absent"});}));return result;}
function classify(grain:ReturnType<typeof generateGrainCandidateArtifact>,truth:GrainTruth){const assessments:Array<{family:string;classification:string;reason:string}>=[];const sourceBlocker=grain.diagnostics.sourceIssues.some((item)=>item.classification==="source_blocker"),pruned=grain.diagnostics.compositeSearch.prunedColumns.some((item)=>item.reason==="global_eligible_column_bound");if(sourceBlocker)assessments.push({family:"all",classification:"structural_blocker",reason:"source-level physical blocker"});if(pruned)assessments.push({family:"composite_identity",classification:"policy_pruning",reason:"eligible-column global bound"});const expectedColumns=[...new Set(truth.candidateKeys.flat())],actualColumns=new Set(grain.rowIdentityCandidates.flatMap((item)=>item.columns));for(const column of expectedColumns.filter((item)=>!actualColumns.has(item))){const decision=grain.diagnostics.identityColumns.find((item)=>item.physicalColumn===column),reason=decision?.reasons.join("|")??"expected column absent from physical source";let classification="semantic_coverage_dependency";if(/technical|measure|time|phone|formula|free_text/.test(reason))classification="justified_abstention";else if(/mixed|non_null|format|structure|distinct|cardinality|physical_type/.test(reason))classification="insufficient_physical_evidence";else if(!decision)classification="expectation_or_taxonomy_question";assessments.push({family:`identity:${column}`,classification,reason});}if(!grain.parentIdentityCandidates.length&&truth.parentKeys.length)assessments.push({family:"parent_identity",classification:grain.rowIdentityCandidates.length?"insufficient_physical_evidence":"semantic_coverage_dependency",reason:"repeated parent plus more-granular child evidence not jointly available"});if(!assessments.length)assessments.push({family:"candidate_set",classification:"justified_abstention",reason:"emitted alternatives match available mechanical evidence"});return assessments;}
function increment(record:Record<string,number>,key:string,amount=1){record[key]=(record[key]??0)+amount;}

describe.sequential("Phase 4A1.1 source-by-source candidate completeness audit",()=>{
  it("audits all governed physical source occurrences without final grain assertions",()=>{const records:Array<Record<string,unknown>>=[],rowUnits:Record<string,number>={},classifications:Record<string,number>={},measureRoles:Record<string,number>={},structural:Record<string,number>={};const uniqueDebt=new Set<string>();let rows=0,columns=0,traces=0,singles=0,composites=0,parents=0,temporal=0,risks=0,onlyUnknown=0,one=0,multiple=0,widthTwo=0,widthThree=0,skipped=0,pruned=0;
    for(const sample of samples){const loaded=sample.sources.map(load),sampleDebt=debt(sample,loaded);sampleDebt.forEach((item)=>uniqueDebt.add(`${item.physicalColumn}|${item.candidateId}|${item.reasonCode}`));for(const source of loaded){const contextual=aggregateContextualEvidence(source.physical,source.candidate,sampleDebt),resolution=resolveSemanticShadow(source.physical,source.candidate,contextual),grain=generateGrainCandidateArtifact(source.physical,resolution,source.rawRows),nonUnknown=grain.grainCandidates.filter((item)=>item.rowUnitClass!=="unknown").length,assessment=classify(grain,sample.dataset.grainTruth);if(nonUnknown===0)onlyUnknown++;else if(nonUnknown===1)one++;else multiple++;rows+=grain.rowCount;columns+=grain.coverage.semanticResolutionCount;traces+=grain.coverage.semanticCandidateTraceCount;singles+=grain.rowIdentityCandidates.filter((item)=>item.kind==="single").length;composites+=grain.compositeKeyCandidates.length;parents+=grain.parentIdentityCandidates.length;temporal+=grain.temporalBehaviors.filter((item)=>item.role!=="no_temporal_basis").length;risks+=grain.aggregationRisks.length;widthTwo+=grain.diagnostics.compositeSearch.widthTwoEvaluated;widthThree+=grain.diagnostics.compositeSearch.widthThreeEvaluated;skipped+=grain.diagnostics.compositeSearch.skippedByGlobalBound;pruned+=grain.coverage.keyColumnsPruned;grain.grainCandidates.forEach((item)=>increment(rowUnits,item.rowUnitClass));grain.measureBehaviors.flatMap((item)=>item.behaviors).forEach((item)=>increment(measureRoles,item));grain.diagnostics.sourceIssues.forEach((item)=>increment(structural,item.classification));assessment.forEach((item)=>increment(classifications,item.classification));
      records.push({occurrenceId:`${sample.id}:${source.key}`,sampleId:sample.id,corpusGroup:sample.group,tuningUse:sample.provenance.tuningUse,sourceIdentity:source.key,rowCount:grain.rowCount,columnCount:grain.columnRoles.length,rowUnitAlternatives:grain.grainCandidates.map((item)=>item.rowUnitClass),onlyUnknown:nonUnknown===0,singleIdentityCandidates:grain.rowIdentityCandidates.filter((item)=>item.kind==="single"),compositeIdentityCandidates:grain.compositeKeyCandidates,parentCandidates:grain.parentIdentityCandidates,temporalBasisAlternatives:grain.temporalBehaviors,measureRoleObservations:grain.measureBehaviors,aggregationRisks:grain.aggregationRisks,structuralLimitations:grain.limitations,semanticDependencies:grain.grainCandidates.flatMap((item)=>item.semanticDependencies),candidateAbsenceEffects:grain.grainDebt,candidateGenerationReasons:grain.diagnostics.candidateGenerationReasons,candidateExclusions:grain.diagnostics.candidateExclusions,identityColumnDecisions:grain.diagnostics.identityColumns,compositeSearch:grain.diagnostics.compositeSearch,sourceIssues:grain.diagnostics.sourceIssues,completenessAssessment:assessment,upstream:{semanticResolutionCount:grain.coverage.semanticResolutionCount,semanticCandidateTraceCount:grain.coverage.semanticCandidateTraceCount},isolation:{finalGrain:false,crossSourceRelationships:false,productionWiring:false}});}}
    expect(records).toHaveLength(37);expect(rows).toBe(36410);expect(columns).toBe(752);expect(traces).toBe(1194);expect(uniqueDebt.size).toBe(10);expect(records.every((item)=>((item.isolation as Record<string,boolean>).finalGrain===false&&(item.isolation as Record<string,boolean>).crossSourceRelationships===false))).toBe(true);
    const audit={schemaVersion:"lightbi.phase-4a1-1-grain-candidate-coverage-audit.v1",date:"2026-07-12",corpusVersion:manifest.corpusVersion,grainPolicy:{version:GRAIN_CANDIDATE_POLICY.schemaVersion,sha256:grainCandidatePolicyHash(),previousVersion:"lightbi.grain-candidate-policy.v1",change:"Add conservative unresolved physical identity hypotheses, scoped structural diagnostics, temporal repetition, and complete pruning diagnostics."},summary:{governedCases:samples.length,physicalSourceOccurrences:records.length,fullFileRows:rows,semanticResolutionsCovered:columns,semanticCandidateTracesAvailable:traces,upstreamAliasCollisionsPreserved:84,upstreamBroadOccurrencesGoverned:18,candidateAbsenceDebtRepresented:uniqueDebt.size,singleKeyCandidates:singles,compositeKeyCandidates:composites,parentKeyCandidates:parents,temporalBasisObservations:temporal,aggregationRisks:risks,widthTwoCombinationsEvaluated:widthTwo,widthThreeCombinationsEvaluated:widthThree,combinationsSkippedByBound:skipped,keyColumnsPrunedByBound:pruned,sourcesByNonUnknownAlternatives:{onlyUnknown,one,multiple}},rowUnitDistribution:rowUnits,measureRoleDistribution:measureRoles,structuralIssueClassification:structural,completenessClassification:classifications,genericDefects:[{id:"physical_identifier_under_generation",disposition:"corrected",reproduction:"stable unresolved structured string codes were omitted when semantic identifier candidates were absent"},{id:"iso_timestamp_identity_false_positive",disposition:"corrected",reproduction:"ISO timestamp strings containing T/Z passed the initial physical identifier structure check"},{id:"structural_blocker_visibility",disposition:"corrected",reproduction:"Phase 4A1 counted only artifact limitations and did not expose physical issue scope"},{id:"composite_pruning_visibility",disposition:"corrected",reproduction:"Phase 4A1 reported aggregate evaluation counts without per-column or per-combination exclusion reasons"}],verification:{phase4Targeted:{filesPassed:4,testsPassed:30},phase3B2:{filesPassed:4,testsPassed:18},phase3B1Phase3APhase2:{filesPassed:7,testsPassed:40},phase1AndLegacySelection:{filesPassed:8,testsPassed:101},typescriptNoEmit:"passed",diffCheck:"passed",fullDesktopSuite:{filesPassed:107,filesFailed:4,testsPassed:909,baselineTestsFailed:9,newOwnedFailures:0}},preservation:{phase2ArtifactsChanged:false,semanticResolutionPolicyVersion:"lightbi.semantic-resolution-policy.v2",semanticResolutionPolicySha256:"064e6861cc208e7d35074d9b872e0d4a11dfacdbc850e6d017c24f32462d6ad3",semanticCandidatesManufactured:0,finalSemanticResolutionsManufactured:0,finalGrainEmitted:false,crossSourceRelationshipsInferred:false,productionWiring:false,domainSupportManifestPopulated:false},records,limitations:["Corpus grainTruth is audited non-infallible evidence and is not consumed by production rules.","Candidate counts and completeness classifications are not grain accuracy.","Holdout, adversarial, and multi-file occurrences did not tune policy."]};
    if(process.env.LIGHTBI_WRITE_PHASE4A11_AUDIT==="1")fs.writeFileSync(path.join(ROOT,"docs/architecture/phase-4a1-1-grain-candidate-coverage-audit.json"),`${JSON.stringify(audit,null,2)}\n`);
  },180_000);
});
