import type { SemanticResolutionState } from "./semantic-resolution-contracts";

export const GRAIN_CANDIDATE_ARTIFACT_VERSION = "lightbi.grain-candidate-artifact.v2" as const;
export const GRAIN_CANDIDATE_POLICY_VERSION = "lightbi.grain-candidate-policy.v2" as const;

export type RowUnitClass = "entity_record"|"event_record"|"document_record"|"line_record"|"snapshot_record"|"interval_record"|"aggregate_record"|"mapping_record"|"mixed_structure"|"unknown";
export type GrainEvidenceFamily = "identity_structure"|"uniqueness_and_repetition"|"parent_child_structure"|"temporal_structure"|"dimension_measure_structure"|"semantic_role_compatibility"|"structural_integrity"|"aggregation_risk";
export type GrainEvidenceDirection = "supports"|"conflicts"|"mixed"|"neutral"|"unavailable";
export type GrainEvidenceV1={evidenceId:string;family:GrainEvidenceFamily;direction:GrainEvidenceDirection;explanationCode:string;physicalColumns:string[];provenance:"full_file_profile"|"full_file_rows"|"semantic_resolution"|"representative_evidence";semanticRuleIds:string[];limitations:string[]};
export type IdentityEvidenceLevel="resolved_semantic"|"ambiguous_semantic"|"unresolved_physical"|"none";
export type ColumnRoleObservationV1={sourceColumnIndex:number;physicalColumn:string;technical:boolean;physicalTypes:string[];nonNullRatio:number;distinctCount:number;cardinalityMode:"exact"|"lower_bound";uniquenessRatio:number|null;semanticState:SemanticResolutionState;semanticCandidateId:string|null;semanticAlternativeCandidateIds:string[];semanticRole:string|null;semanticType:string|null;semanticRuleIds:string[];identityEvidenceLevel:IdentityEvidenceLevel;identityEligible:boolean;dimensionCandidate:boolean;measureCandidate:boolean;temporalCandidate:boolean;limitations:string[]};
export type RowIdentityCandidateV1={candidateId:string;columns:string[];kind:"single"|"composite";width:1|2|3;nonNullRatio:number;uniquenessRatio:number|null;exactFullFileEvaluation:boolean;businessIdentityProven:false;identityEvidenceLevel:Exclude<IdentityEvidenceLevel,"none">;evidence:GrainEvidenceV1[];limitations:string[]};
export type CompositeKeyCandidateV1=RowIdentityCandidateV1&{kind:"composite";combinationsEvaluated:number;prunedColumnCount:number};
export type ParentIdentityCandidateV1={candidateId:string;columns:string[];repetitionRatio:number;identityEvidenceLevel:Exclude<IdentityEvidenceLevel,"none">;childIdentityCandidateIds:string[];stableRepeatedAttributeColumns:string[];varyingChildColumns:string[];evidence:GrainEvidenceV1[];limitations:string[]};
export type TemporalRole="event_time"|"effective_time"|"snapshot_time"|"interval_start"|"interval_end"|"reporting_period"|"no_temporal_basis"|"unresolved_temporal_basis";
export type TemporalBehaviorV1={physicalColumn:string|null;role:TemporalRole;semanticState:SemanticResolutionState|null;distinctTimeCount:number|null;repeatedEntityAcrossTime:boolean|null;fullFileEvidence:boolean;evidence:GrainEvidenceV1[];limitations:string[]};
export type MeasureBehaviorKind="additive_candidate"|"semi_additive_candidate"|"non_additive_candidate"|"repeated_measure_risk"|"dimension_or_code_candidate"|"unresolved_measure_role";
export type MeasureBehaviorV1={physicalColumn:string;behaviors:MeasureBehaviorKind[];semanticState:SemanticResolutionState;semanticCandidateId:string|null;repeatedWithinParent:boolean|null;safeToAggregate:false;evidence:GrainEvidenceV1[];limitations:string[]};
export type RepetitionPatternV1={columns:string[];pattern:"unique"|"repeated"|"constant_within_parent"|"varying_within_parent"|"unavailable";count:number;provenance:"full_file_profile"|"full_file_rows";evidenceReferences:string[]};
export type AggregationRiskV1={riskId:string;kind:"repeated_parent_measure"|"snapshot_across_time"|"rate_or_ratio"|"identifier_or_code"|"uncertain_semantics"|"mixed_structure";physicalColumns:string[];severity:"info"|"material";explanationCode:string;evidenceReferences:string[]};
export type GrainCandidateV1={candidateId:string;rowUnitClass:RowUnitClass;rowIdentityCandidateIds:string[];parentIdentityCandidateIds:string[];temporalRoles:TemporalRole[];dimensionColumns:string[];measureColumns:string[];supportingEvidence:GrainEvidenceV1[];conflictingEvidence:GrainEvidenceV1[];structuralLimitations:string[];semanticDependencies:Array<{physicalColumn:string;state:SemanticResolutionState;candidateId:string|null;alternativeCandidateIds:string[];ruleIds:string[]}>;aggregationRiskIds:string[];provenance:string[]};
export type GrainLimitationV1={code:string;severity:"info"|"material";scope:"source"|"candidate"|"evidence"|"governance";explanation:string;physicalColumns:string[]};
export type GrainDebtV1={physicalColumn:string;candidateId:string;reasonCode:string;effect:"identity_hypothesis_limited"|"parent_hypothesis_limited"|"semantic_role_unavailable"};
export type IdentityColumnDecisionV1={sourceColumnIndex:number;physicalColumn:string;eligible:boolean;evidenceLevel:IdentityEvidenceLevel;reasons:string[];formatStability:number|null};
export type CompositeSearchDiagnosticV1={eligibleColumnCount:number;eligibleColumns:string[];prunedColumns:Array<{physicalColumn:string;reason:string}>;widthTwoEvaluated:number;widthThreeEvaluated:number;skippedByGlobalBound:number;uniqueCombinations:string[][];rejected:Array<{columns:string[];reason:"null_coverage"|"not_unique"|"mixed_or_unstable"|"semantic_risk"}>;deterministicOrder:"source_column_index"};
export type GrainCandidateDiagnosticsV1={identityColumns:IdentityColumnDecisionV1[];compositeSearch:CompositeSearchDiagnosticV1;candidateGenerationReasons:Record<RowUnitClass,string[]>;candidateExclusions:Array<{rowUnitClass:RowUnitClass;reason:string}>;sourceIssues:Array<{code:string;severity:string;physicalColumn:string|null;classification:"source_blocker"|"candidate_limitation"|"evidence_limitation"|"harmless_issue"}>;duplicateEvidenceRemoved:number};
export type GrainPolicyV1={schemaVersion:typeof GRAIN_CANDIDATE_POLICY_VERSION;maxCompositeWidth:3;maxEligibleKeyColumns:number;maxCompositeCombinations:number;minimumIdentityNonNullRatio:number;minimumIdentityUniquenessRatio:number;minimumPhysicalFormatStability:number;rules:Array<{ruleId:string;description:string}>;forbiddenInference:string[];extensionBoundary:{allowed:string[];forbidden:string[]}};
export type GrainCandidateArtifactV1={schemaVersion:typeof GRAIN_CANDIDATE_ARTIFACT_VERSION;sourceId:string;sourceHash:{algorithm:"sha256"|"unknown";value:string}|null;physicalArtifactVersion:string;semanticResolutionArtifactVersion:string;registryVersion:string;semanticResolutionPolicyVersion:string;semanticResolutionPolicyHash:string;grainPolicyVersion:typeof GRAIN_CANDIDATE_POLICY_VERSION;grainPolicyHash:string;rowCount:number;columnRoles:ColumnRoleObservationV1[];rowIdentityCandidates:RowIdentityCandidateV1[];compositeKeyCandidates:CompositeKeyCandidateV1[];parentIdentityCandidates:ParentIdentityCandidateV1[];temporalBehaviors:TemporalBehaviorV1[];measureBehaviors:MeasureBehaviorV1[];repetitionPatterns:RepetitionPatternV1[];aggregationRisks:AggregationRiskV1[];grainCandidates:GrainCandidateV1[];grainDebt:GrainDebtV1[];diagnostics:GrainCandidateDiagnosticsV1;coverage:{physicalColumnCount:number;semanticResolutionCount:number;semanticCandidateTraceCount:number;rawRowsEvaluated:number;keyCombinationsEvaluated:number;keyColumnsPruned:number};limitations:GrainLimitationV1[];finalGrainResolution:{executed:false};crossSourceRelationships:{executed:false};productionWiring:{executed:false}};
