import {describe,expect,it} from "vitest";
import {SEMANTIC_SIGNAL_REGISTRY_V1} from "../semantic-registry";
import {aggregateContextualEvidence} from "./contextual-evidence-aggregator";
import {canonicalJson} from "./contextual-evidence-policy";
import {generateGrainCandidateArtifact} from "./grain-candidate-engine";
import {GRAIN_CANDIDATE_POLICY,grainCandidatePolicyHash} from "./grain-candidate-policy";
import {profilePhysicalSource} from "./profiler";
import {generateSemanticCandidateArtifact} from "./semantic-candidate-engine";
import {resolveSemanticShadow} from "./semantic-resolver";
function pipeline(rows:unknown[][],ids:string[],debt:Array<{physicalColumn:string;candidateId:string;reasonCode:string}>=[]){const physical=profilePhysicalSource({schemaVersion:"lightbi.physical-source-input.v1",source:{sourceId:"grain-test",kind:"unknown",label:"grain-test",hash:{algorithm:"sha256",value:"stable"}},rawRows:rows});const candidate=generateSemanticCandidateArtifact(physical,{registry:SEMANTIC_SIGNAL_REGISTRY_V1.filter((item)=>ids.includes(item.canonicalId))}),contextual=aggregateContextualEvidence(physical,candidate,debt),resolution=resolveSemanticShadow(physical,candidate,contextual);return{physical,resolution,grain:generateGrainCandidateArtifact(physical,resolution,rows)};}
describe("Phase 4A1 universal grain candidate foundation",()=>{
it("creates bounded row identity, composite key, parent and line candidates without final selection",()=>{const {grain}=pipeline([["order","shipment","quantity"],[1,"S-1",10],[1,"S-2",20],[2,"S-3",30]],["order","shipment","quantity"]);expect(grain.rowIdentityCandidates.some((item)=>item.columns.includes("shipment"))).toBe(true);expect(grain.compositeKeyCandidates.every((item)=>item.width<=3)).toBe(true);expect(grain.parentIdentityCandidates.some((item)=>item.columns.includes("order"))).toBe(true);expect(grain.grainCandidates.map((item)=>item.rowUnitClass)).toContain("line_record");expect(grain.finalGrainResolution.executed).toBe(false);const artifactKeys=JSON.stringify(grain,(_,value)=>value);expect(artifactKeys).not.toMatch(/"selectedGrain"|"grainConfidence"|"grainRank"|"winner"/);});
it("keeps technical indexes and unique monetary values out of business keys",()=>{const {grain}=pipeline([["__PowerAppsId__","shipment","unit_price"],["a886d124-31d9-4a9a-a3e2-000000000001","S-1",11],["a886d124-31d9-4a9a-a3e2-000000000002","S-2",12]],["shipment","unit_price"]);expect(grain.columnRoles.find((item)=>item.physicalColumn==="__PowerAppsId__")?.technical).toBe(true);expect(grain.rowIdentityCandidates.flatMap((item)=>item.columns)).not.toContain("__PowerAppsId__");expect(grain.rowIdentityCandidates.flatMap((item)=>item.columns)).not.toContain("unit_price");expect(grain.measureBehaviors.find((item)=>item.physicalColumn==="unit_price")?.behaviors).toContain("non_additive_candidate");});
it("treats percentages, averages, ratings and unresolved numerics conservatively",()=>{const {grain}=pipeline([["margin_pct","rating_score","unknown_number"],[.1,4,100],[.2,5,200]],["margin_pct","rating_score"]);expect(grain.measureBehaviors.find((item)=>item.physicalColumn==="margin_pct")?.behaviors).toContain("non_additive_candidate");expect(grain.measureBehaviors.find((item)=>item.physicalColumn==="rating_score")?.behaviors).toContain("dimension_or_code_candidate");expect(grain.measureBehaviors.find((item)=>item.physicalColumn==="unknown_number")?.behaviors).toContain("unresolved_measure_role");expect(grain.measureBehaviors.every((item)=>item.safeToAggregate===false)).toBe(true);});
it("retains event, snapshot and interval alternatives from universal temporal mechanics",()=>{const event=pipeline([["shipment","delivery_date"],["S-1","2026-01-01"],["S-2","2026-01-02"]],["shipment","delivery_date"]).grain;expect(event.grainCandidates.map((item)=>item.rowUnitClass)).toContain("event_record");const snapshot=pipeline([["asset","time_period","balance"],["A-1","2026-01-01",10],["A-2","2026-01-01",20]],["asset","time_period","balance"]).grain;expect(snapshot.grainCandidates.map((item)=>item.rowUnitClass)).toContain("snapshot_record");expect(snapshot.measureBehaviors.find((item)=>item.physicalColumn==="balance")?.behaviors).toContain("semi_additive_candidate");const interval=pipeline([["asset","effective_date","expiration_date"],["A-1","2026-01-01","2026-12-31"]],["asset","effective_date","expiration_date"]).grain;expect(interval.grainCandidates.map((item)=>item.rowUnitClass)).toContain("interval_record");});
it("retains entity, mapping, aggregate, mixed and unknown alternatives",()=>{expect(pipeline([["asset"],["A-1"],["A-2"]],["asset"]).grain.grainCandidates.map((item)=>item.rowUnitClass)).toContain("entity_record");expect(pipeline([["asset","employee_id"],["A-1","E-1"],["A-2","E-2"]],["asset","employee_id"]).grain.grainCandidates.map((item)=>item.rowUnitClass)).toContain("mapping_record");expect(pipeline([["quantity"],[10],[20]],["quantity"]).grain.grainCandidates.map((item)=>item.rowUnitClass)).toContain("aggregate_record");const mixed=pipeline([["asset","quantity"],["A-1",10],["A-2","bad"]],["asset","quantity"]).grain;expect(mixed.grainCandidates.map((item)=>item.rowUnitClass)).toContain("mixed_structure");expect(mixed.grainCandidates.map((item)=>item.rowUnitClass)).toContain("unknown");});
it("propagates semantic uncertainty and candidate absence while retaining a limited physical identity hypothesis",()=>{const {grain}=pipeline([["opaque_id","quantity"],["X-1",10],["X-2",20]],["quantity"],[{physicalColumn:"opaque_id",candidateId:"asset",reasonCode:"missing_candidate"}]);const role=grain.columnRoles.find((item)=>item.physicalColumn==="opaque_id");expect(role?.identityEligible).toBe(true);expect(role?.identityEvidenceLevel).toBe("unresolved_physical");expect(role?.semanticCandidateId).toBeNull();expect(grain.rowIdentityCandidates.find((item)=>item.columns.includes("opaque_id"))?.businessIdentityProven).toBe(false);expect(grain.grainDebt).toHaveLength(1);expect(grain.grainDebt[0].candidateId).toBe("asset");expect(grain.finalGrainResolution.executed).toBe(false);});
it("is deterministic, bounded, row-order neutral, hash-governed and fail-closed",()=>{const base=pipeline([["order","shipment"],[1,"S-1"],[1,"S-2"],[2,"S-3"]],["order","shipment"]),reordered=pipeline([["order","shipment"],[2,"S-3"],[1,"S-2"],[1,"S-1"]],["order","shipment"]);expect(canonicalJson(base.grain)).toBe(canonicalJson(generateGrainCandidateArtifact(base.physical,base.resolution,[["order","shipment"],[1,"S-1"],[1,"S-2"],[2,"S-3"]])));expect(base.grain.grainCandidates.map((item)=>item.rowUnitClass)).toEqual(reordered.grain.grainCandidates.map((item)=>item.rowUnitClass));expect(base.grain.coverage.keyCombinationsEvaluated).toBeLessThanOrEqual(GRAIN_CANDIDATE_POLICY.maxCompositeCombinations);expect(grainCandidatePolicyHash({a:1,b:2})).toBe(grainCandidatePolicyHash({b:2,a:1}));expect(grainCandidatePolicyHash({...GRAIN_CANDIDATE_POLICY,forbiddenInference:[...GRAIN_CANDIDATE_POLICY.forbiddenInference,"mutation"]})).not.toBe(grainCandidatePolicyHash());expect(()=>generateGrainCandidateArtifact(base.physical,{...base.resolution,sourceId:"other"},[["order","shipment"],[1,"S-1"],[1,"S-2"],[2,"S-3"]])).toThrow("ARTIFACT_MISMATCH");expect(()=>generateGrainCandidateArtifact(base.physical,base.resolution,[["order","shipment"]])).toThrow("RAW_ROW_MATRIX_MISMATCH");});
it("rejects sparse and mixed identifier keys while retaining explicit limitations",()=>{const sparse=pipeline([["shipment","quantity"],["S-1",1],["",2],["",3]],["shipment","quantity"]).grain;expect(sparse.rowIdentityCandidates.flatMap((item)=>item.columns)).not.toContain("shipment");const mixed=pipeline([["shipment","quantity"],["S-1",1],[2,2]],["shipment","quantity"]).grain;expect(mixed.rowIdentityCandidates.flatMap((item)=>item.columns)).not.toContain("shipment");expect(mixed.columnRoles.find((item)=>item.physicalColumn==="shipment")?.limitations).toContain("mixed_type");});
it("flags repeated parent totals and retains document and event alternatives without domain rules",()=>{const line=pipeline([["order","shipment","quantity","parent_total"],[1,"S-1",10,100],[1,"S-2",20,100],[2,"S-3",30,50]],["order","shipment","quantity"]).grain;expect(line.parentIdentityCandidates.length).toBeGreaterThan(0);expect(line.measureBehaviors.find((item)=>item.physicalColumn==="parent_total")?.behaviors).toContain("repeated_measure_risk");expect(line.aggregationRisks.map((item)=>item.kind)).toContain("repeated_parent_measure");const header=pipeline([["shipment","quantity"],["S-1",100],["S-2",200]],["shipment","quantity"]).grain;expect(header.grainCandidates.map((item)=>item.rowUnitClass)).toContain("document_record");const event=pipeline([["delivery_date","quantity"],["2026-01-01",1],["2026-01-02",2]],["delivery_date","quantity"]).grain;expect(event.grainCandidates.map((item)=>item.rowUnitClass)).toContain("event_record");});
it("preserves ambiguous identifier alternatives as limited candidates only",()=>{const {grain}=pipeline([["order","quantity"],["O-1",1],["O-2",2]],["order","sales_order","quantity"]);const role=grain.columnRoles.find((item)=>item.physicalColumn==="order");if(role?.semanticState==="ambiguous"){expect(role.semanticAlternativeCandidateIds.length).toBeGreaterThan(0);expect(grain.rowIdentityCandidates.find((item)=>item.columns.includes("order"))?.limitations.join(" ")).toMatch(/ambiguous/i);}expect(grain.finalGrainResolution.executed).toBe(false);});
});
