import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";
import { aggregateContextualEvidence } from "./contextual-evidence-aggregator";
import type { CandidateAbsenceDebtV1 } from "./contextual-evidence-contracts";
import { generateGrainCandidateArtifact } from "./grain-candidate-engine";
import type { RowUnitClass } from "./grain-candidate-contracts";
import { profilePhysicalSource } from "./profiler";
import { generateSemanticCandidateArtifact } from "./semantic-candidate-engine";
import { resolveSemanticShadow } from "./semantic-resolver";

const ROOT=path.resolve(__dirname,"../../../../..");
type Group="golden"|"holdout"|"adversarial"|"multi_file";
type Source={path:string;sheet:string;sha256:string};
type Sample={id:string;group:Group;provenance:{tuningUse:"allowed"|"forbidden"};sources:Source[];recognition:{requiredMappings:Array<{physicalColumn:string;canonicalSignal:string}>;expectedAmbiguousMappings:Array<{physicalColumn:string;candidateSignals:string[]}>}};
type Expectation={id:string;group:Group;requiredCandidateClasses:RowUnitClass[];allowedCandidateClasses:RowUnitClass[]};
const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,"sample-corpus/versions/1.4.0/manifest.json"),"utf8")) as {groundTruthFiles:Array<{path:string}>;groups:Record<Group,{tuningAllowed:boolean}>};
const samples=manifest.groundTruthFiles.flatMap((entry)=>(JSON.parse(fs.readFileSync(path.join(ROOT,entry.path),"utf8")) as {samples:Sample[]}).samples);
const expectationDocument=JSON.parse(fs.readFileSync(path.join(ROOT,"sample-corpus/grain-candidate-expectations.v1.json"),"utf8")) as {schemaVersion:string;governance:{finalGrainAssertionsForbidden:boolean;sourceBySourceOnly:boolean;validationGroupsTuningForbidden:Group[]};samples:Expectation[]};
const expectationById=new Map(expectationDocument.samples.map((item)=>[item.id,item]));
type Loaded={rawRows:unknown[][];physical:ReturnType<typeof profilePhysicalSource>;candidate:ReturnType<typeof generateSemanticCandidateArtifact>};
const cache=new Map<string,Loaded>();
function load(source:Source):Loaded{const key=`${source.path}#${source.sheet}`,cached=cache.get(key);if(cached)return cached;const bytes=fs.readFileSync(path.join(ROOT,source.path));expect(crypto.createHash("sha256").update(bytes).digest("hex")).toBe(source.sha256);const book=XLSX.read(bytes,{raw:true}),sheet=book.Sheets[source.sheet]??book.Sheets[book.SheetNames[0]];if(!sheet)throw new Error(`missing sheet ${key}`);const rawRows=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:"",blankrows:true});const physical=profilePhysicalSource({schemaVersion:"lightbi.physical-source-input.v1",source:{sourceId:key,kind:"local_file",label:path.basename(source.path),hash:{algorithm:"sha256",value:source.sha256}},rawRows}),candidate=generateSemanticCandidateArtifact(physical),loaded={rawRows,physical,candidate};cache.set(key,loaded);return loaded;}
function debt(sample:Sample,all:Loaded[]):CandidateAbsenceDebtV1[]{const ids=(column:string)=>new Set(all.flatMap(({candidate})=>candidate.observations.filter((item)=>item.physicalColumn===column).flatMap((item)=>item.candidateSet.candidates.map((candidate)=>candidate.candidateId))));const result:CandidateAbsenceDebtV1[]=[];sample.recognition.requiredMappings.forEach((mapping)=>{if(!ids(mapping.physicalColumn).has(mapping.canonicalSignal))result.push({physicalColumn:`${sample.id}:${mapping.physicalColumn}`,candidateId:mapping.canonicalSignal,reasonCode:"required_candidate_absent"});});sample.recognition.expectedAmbiguousMappings.forEach((mapping)=>mapping.candidateSignals.forEach((candidateId)=>{if(!ids(mapping.physicalColumn).has(candidateId))result.push({physicalColumn:`${sample.id}:${mapping.physicalColumn}`,candidateId,reasonCode:"contextual_candidate_absent"});}));return result;}
function increment(record:Record<string,number>,key:string,amount=1){record[key]=(record[key]??0)+amount;}

describe.sequential("Phase 4A1 grain candidates across governed corpus",()=>{
  it("keeps the separate expectation layer non-final and validation groups tuning-forbidden",()=>{
    expect(expectationDocument.schemaVersion).toBe("lightbi.grain-candidate-expectations.v1");
    expect(expectationDocument.governance.finalGrainAssertionsForbidden).toBe(true);
    expect(expectationDocument.governance.sourceBySourceOnly).toBe(true);
    expect(expectationDocument.samples).toHaveLength(30);
    expect(new Set(expectationDocument.samples.map((item)=>item.id)).size).toBe(30);
    for(const sample of samples){expect(expectationById.has(sample.id),sample.id).toBe(true);expect(sample.provenance.tuningUse).toBe(manifest.groups[sample.group].tuningAllowed?"allowed":"forbidden");if(sample.group!=="golden")expect(expectationDocument.governance.validationGroupsTuningForbidden).toContain(sample.group);}
  });
  it("preserves candidate evidence source-by-source without selecting final grain",()=>{
    const byClass:Record<string,number>={},byGroup:Record<string,{sources:number;candidates:number;keys:number;parents:number;debt:number}>={},evidenceFamilies:Record<string,number>={},provenance:Record<string,number>={},measureKinds:Record<string,number>={};
    const uniqueDebt=new Set<string>();let sources=0,rows=0,columns=0,traces=0,singles=0,composites=0,parents=0,temporal=0,risks=0,ambiguousDependencies=0,structuralBlockers=0,keyCombinations=0,keyColumnsPruned=0,zero=0,one=0,multiple=0;
    for(const sample of samples){const all=sample.sources.map(load),sampleDebt=debt(sample,all),expected=expectationById.get(sample.id)!;sampleDebt.forEach((item)=>uniqueDebt.add(`${item.physicalColumn}|${item.candidateId}|${item.reasonCode}`));for(let index=0;index<all.length;index++){const loaded=all[index],contextual=aggregateContextualEvidence(loaded.physical,loaded.candidate,sampleDebt),resolution=resolveSemanticShadow(loaded.physical,loaded.candidate,contextual),grain=generateGrainCandidateArtifact(loaded.physical,resolution,loaded.rawRows);sources++;rows+=grain.rowCount;columns+=grain.coverage.semanticResolutionCount;traces+=grain.coverage.semanticCandidateTraceCount;singles+=grain.rowIdentityCandidates.filter((item)=>item.kind==="single").length;composites+=grain.compositeKeyCandidates.length;parents+=grain.parentIdentityCandidates.length;temporal+=grain.temporalBehaviors.filter((item)=>!["no_temporal_basis","unresolved_temporal_basis"].includes(item.role)).length;risks+=grain.aggregationRisks.length;keyCombinations+=grain.coverage.keyCombinationsEvaluated;keyColumnsPruned+=grain.coverage.keyColumnsPruned;ambiguousDependencies+=grain.grainCandidates.flatMap((item)=>item.semanticDependencies).filter((item)=>item.state==="ambiguous").length;structuralBlockers+=grain.limitations.filter((item)=>item.severity==="material").length;const nonUnknown=grain.grainCandidates.filter((item)=>item.rowUnitClass!=="unknown").length;if(nonUnknown===0)zero++;else if(nonUnknown===1)one++;else multiple++;
      expect(grain.coverage.physicalColumnCount).toBe(loaded.physical.sourceProfile.columns.length);expect(grain.coverage.semanticResolutionCount).toBe(resolution.columns.length);expect(grain.coverage.semanticCandidateTraceCount).toBe(resolution.candidatePreservationProof.outputCandidateTraceCount);expect(grain.finalGrainResolution.executed).toBe(false);expect(grain.crossSourceRelationships.executed).toBe(false);expect(grain.productionWiring.executed).toBe(false);expect(grain.grainCandidates.map((item)=>item.rowUnitClass)).toEqual(expect.arrayContaining(expected.requiredCandidateClasses));expect(grain.grainCandidates.every((item)=>expected.allowedCandidateClasses.includes(item.rowUnitClass))).toBe(true);expect(grain.compositeKeyCandidates.every((item)=>item.width<=3)).toBe(true);expect(grain.columnRoles.map((item)=>item.physicalColumn)).toEqual(loaded.physical.sourceProfile.columns.map((item)=>item.physicalColumnName));expect(grain.grainDebt).toHaveLength(sampleDebt.length);
      grain.grainCandidates.forEach((item)=>{increment(byClass,item.rowUnitClass);item.supportingEvidence.concat(item.conflictingEvidence).forEach((entry)=>{increment(evidenceFamilies,entry.family);increment(provenance,entry.provenance);});});grain.rowIdentityCandidates.flatMap((item)=>item.evidence).concat(grain.parentIdentityCandidates.flatMap((item)=>item.evidence),grain.temporalBehaviors.flatMap((item)=>item.evidence),grain.measureBehaviors.flatMap((item)=>item.evidence)).forEach((entry)=>{increment(evidenceFamilies,entry.family);increment(provenance,entry.provenance);});grain.measureBehaviors.flatMap((item)=>item.behaviors).forEach((kind)=>increment(measureKinds,kind));const group=byGroup[sample.group]??{sources:0,candidates:0,keys:0,parents:0,debt:0};group.sources++;group.candidates+=grain.grainCandidates.length;group.keys+=grain.rowIdentityCandidates.length;group.parents+=grain.parentIdentityCandidates.length;group.debt+=grain.grainDebt.length;byGroup[sample.group]=group;}}
    expect(sources).toBeGreaterThanOrEqual(30);expect(columns).toBe(752);expect(traces).toBe(1202);expect(uniqueDebt.size).toBe(10);expect(Object.keys(byClass)).toContain("unknown");expect(Object.keys(byGroup).sort()).toEqual(["adversarial","golden","holdout","multi_file"]);expect(provenance.representative_evidence??0).toBe(0);
    const audit={schemaVersion:"lightbi.phase-4a1-grain-candidate-audit.v1",date:"2026-07-12",scope:"candidate_and_evidence_only",summary:{samples:samples.length,physicalSources:sources,rowsEvaluated:rows,semanticResolutionsCovered:columns,semanticCandidateTracesAvailableUpstream:traces,uniqueCandidateAbsenceDebtCarried:uniqueDebt.size,singleKeyCandidates:singles,compositeKeyCandidates:composites,parentKeyCandidates:parents,temporalBasisCandidates:temporal,aggregationRisks:risks,ambiguousSemanticDependencies:ambiguousDependencies,structuralBlockers,keyCombinationsEvaluated:keyCombinations,keyColumnsPruned,sourcesByNonUnknownCandidateCount:{zero,one,multiple}},grainCandidatesByClass:byClass,measureBehaviors:measureKinds,evidenceFamilies,evidenceProvenance:provenance,validationByGroup:byGroup,governance:{finalGrainResolution:false,crossSourceRelationships:false,productionWiring:false,domainSupportManifestPopulated:false},limitations:["Diagnostics describe candidate coverage, not grain accuracy.","Existing corpus grain truth is audited but not treated as infallible or as a final-winner assertion.","Validation-only groups did not tune production policy."]};
    if(process.env.LIGHTBI_WRITE_PHASE4A1_AUDIT==="1")fs.writeFileSync(path.join(ROOT,"docs/architecture/phase-4a1-grain-candidate-audit.json"),`${JSON.stringify(audit,null,2)}\n`);
  },180_000);
});
