import fs from "node:fs";import path from "node:path";import {describe,expect,it} from "vitest";import {SEMANTIC_SIGNAL_REGISTRY_V1} from "../semantic-registry";import {aggregateContextualEvidence} from "./contextual-evidence-aggregator";import {generateGrainCandidateArtifact} from "./grain-candidate-engine";import type {GrainCandidateArtifactV1} from "./grain-candidate-contracts";import type {GrainAxis,GrainAxisState} from "./grain-resolution-contracts";import {certaintyRelation,validateGrainResolution} from "./grain-resolution-validation";import {resolveGrainSignatureShadow} from "./grain-resolver";import {profilePhysicalSource} from "./profiler";import {generateSemanticCandidateArtifact} from "./semantic-candidate-engine";import {resolveSemanticShadow} from "./semantic-resolver";
const ROOT=path.resolve(__dirname,"../../../../.."),ids=["asset","order","shipment","report_date","quantity","time_period","balance","effective_date","expiration_date"];
function build(rows:unknown[][],selected=ids,debt:Array<{physicalColumn:string;candidateId:string;reasonCode:string}>=[]){const physical=profilePhysicalSource({schemaVersion:"lightbi.physical-source-input.v1",source:{sourceId:"grain-counterfactual",kind:"unknown",label:"grain-counterfactual",hash:{algorithm:"sha256",value:"stable"}},rawRows:rows}),candidate=generateSemanticCandidateArtifact(physical,{registry:SEMANTIC_SIGNAL_REGISTRY_V1.filter((item)=>selected.includes(item.canonicalId))}),context=aggregateContextualEvidence(physical,candidate,debt),semantic=resolveSemanticShadow(physical,candidate,context);return generateGrainCandidateArtifact(physical,semantic,rows);}
const resolve=(grain:GrainCandidateArtifactV1)=>resolveGrainSignatureShadow(grain,{sourceId:grain.sourceId,sourceHash:grain.sourceHash});const clone=(grain:GrainCandidateArtifactV1)=>structuredClone(grain);const axisState=(result:ReturnType<typeof resolve>,axis:GrainAxis):GrainAxisState=>axis==="structural_form"?result.signature.structuralForm.state:axis==="identity_basis"?result.signature.identityBasis.state:axis==="parent_basis"?result.signature.parentBasis.state:axis==="temporal_mode"?result.signature.temporalMode.state:result.signature.aggregationForm.state;
type Mutation={id:string;axis:GrainAxis;base:()=>GrainCandidateArtifactV1;mutate:(grain:GrainCandidateArtifactV1)=>GrainCandidateArtifactV1;expect:"not_increased"|"unchanged_or_incomparable"};
const entity=()=>build([["asset"],["A-1"],["A-2"]]),line=()=>build([["order","shipment","report date","quantity"],[1,"S-1","2026-01-01",10],[1,"S-2","2026-01-02",10],[2,"S-3","2026-01-03",20]]),event=()=>build([["report date","quantity"],["2026-01-01",1],["2026-01-02",2]]),reporting=()=>build([["time_period","quantity"],["2026-01",10],["2026-02",20]]);
const mutations:Mutation[]=[
{id:"remove_identity_evidence_from_entity",axis:"structural_form",base:entity,mutate:g=>{g.rowIdentityCandidates=[];return g},expect:"not_increased"},
{id:"remove_parent_repetition_from_line",axis:"structural_form",base:line,mutate:g=>{g.parentIdentityCandidates=[];return g},expect:"not_increased"},
{id:"remove_child_variation_from_line",axis:"parent_basis",base:line,mutate:g=>{g.parentIdentityCandidates=[];return g},expect:"not_increased"},
{id:"remove_granular_child_identity",axis:"structural_form",base:line,mutate:g=>{g.rowIdentityCandidates=[];return g},expect:"not_increased"},
{id:"resolved_identifier_to_ambiguous",axis:"identity_basis",base:entity,mutate:g=>{g.rowIdentityCandidates.forEach(x=>x.identityEvidenceLevel="ambiguous_semantic");return g},expect:"not_increased"},
{id:"semantic_identifier_to_unresolved_physical",axis:"identity_basis",base:entity,mutate:g=>{g.rowIdentityCandidates.forEach(x=>x.identityEvidenceLevel="unresolved_physical");return g},expect:"not_increased"},
{id:"remove_exact_uniqueness",axis:"identity_basis",base:entity,mutate:g=>{g.rowIdentityCandidates=[];return g},expect:"not_increased"},
{id:"nulls_below_identity_coverage",axis:"identity_basis",base:entity,mutate:()=>build([["asset"],["A-1"],[null],[null]]),expect:"not_increased"},
{id:"mixed_types_on_key",axis:"identity_basis",base:entity,mutate:()=>build([["asset"],["A-1"],[2],[null]]),expect:"not_increased"},
{id:"technical_index_marker",axis:"identity_basis",base:entity,mutate:()=>build([["__index__"],[1],[2]]),expect:"not_increased"},
{id:"add_incomparable_single_key",axis:"identity_basis",base:entity,mutate:g=>{g.rowIdentityCandidates.push({...structuredClone(g.rowIdentityCandidates[0]),candidateId:"identity:other",columns:["other"]});return g},expect:"not_increased"},
{id:"add_incomparable_composite_key",axis:"identity_basis",base:entity,mutate:g=>{g.rowIdentityCandidates.push({...structuredClone(g.rowIdentityCandidates[0]),candidateId:"identity:other+third",columns:["other","third"],kind:"composite",width:2});return g},expect:"not_increased"},
{id:"add_material_candidate_debt",axis:"identity_basis",base:entity,mutate:g=>{g.grainDebt.push({physicalColumn:"asset",candidateId:"asset",reasonCode:"missing",effect:"identity_hypothesis_limited"});return g},expect:"not_increased"},
{id:"add_unrelated_candidate_debt",axis:"temporal_mode",base:event,mutate:g=>{g.grainDebt.push({physicalColumn:"other",candidateId:"asset",reasonCode:"missing",effect:"identity_hypothesis_limited"});return g},expect:"not_increased"},
{id:"remove_event_time_semantics",axis:"temporal_mode",base:event,mutate:g=>{g.grainCandidates=g.grainCandidates.filter(x=>x.rowUnitClass!=="event_record");g.temporalBehaviors.forEach(x=>x.role="unresolved_temporal_basis");return g},expect:"not_increased"},
{id:"event_to_unresolved_temporal_basis",axis:"temporal_mode",base:event,mutate:g=>{g.grainCandidates=g.grainCandidates.filter(x=>x.rowUnitClass!=="event_record");g.temporalBehaviors.forEach(x=>x.role="unresolved_temporal_basis");return g},expect:"not_increased"},
{id:"add_competing_snapshot",axis:"temporal_mode",base:()=>{const g=line(),c=structuredClone(g.grainCandidates[0]);c.candidateId="grain:event-counterfactual";c.rowUnitClass="event_record";g.grainCandidates.push(c);return g},mutate:g=>{const c=structuredClone(g.grainCandidates.find(x=>x.rowUnitClass==="event_record")!);c.candidateId="grain:snapshot-counterfactual";c.rowUnitClass="snapshot_record";g.grainCandidates.push(c);return g},expect:"not_increased"},
{id:"start_end_conflict",axis:"temporal_mode",base:()=>build([["asset","effective_date","expiration_date"],["A-1","2026-01-01","2026-12-31"]]),mutate:g=>{g.grainCandidates=g.grainCandidates.filter(x=>x.rowUnitClass!=="interval_record");return g},expect:"not_increased"},
{id:"remove_reporting_period",axis:"structural_form",base:reporting,mutate:g=>{g.temporalBehaviors=[];g.grainCandidates=g.grainCandidates.filter(x=>x.rowUnitClass!=="aggregate_record");return g},expect:"not_increased"},
{id:"remove_repeated_parent_measure",axis:"aggregation_form",base:line,mutate:g=>{g.aggregationRisks=g.aggregationRisks.filter(x=>x.kind!=="repeated_parent_measure");return g},expect:"not_increased"},
{id:"add_structural_corruption",axis:"structural_form",base:entity,mutate:g=>{g.limitations.push({code:"duplicate_header",severity:"material",scope:"source",explanation:"synthetic",physicalColumns:[]});return g},expect:"not_increased"},
{id:"duplicate_evidence",axis:"identity_basis",base:entity,mutate:g=>{g.rowIdentityCandidates[0].evidence.push(structuredClone(g.rowIdentityCandidates[0].evidence[0]));return g},expect:"not_increased"},
{id:"duplicate_parent_child_evidence",axis:"parent_basis",base:line,mutate:g=>{g.parentIdentityCandidates[0].evidence.push(structuredClone(g.parentIdentityCandidates[0].evidence[0]));return g},expect:"not_increased"},
{id:"duplicate_candidate",axis:"structural_form",base:line,mutate:g=>{g.grainCandidates.push({...structuredClone(g.grainCandidates[0]),candidateId:"duplicate:candidate"});return g},expect:"not_increased"},
{id:"shuffle_evidence_order",axis:"structural_form",base:line,mutate:g=>{g.grainCandidates.forEach(x=>{x.supportingEvidence.reverse();x.conflictingEvidence.reverse()});return g},expect:"unchanged_or_incomparable"},
{id:"shuffle_candidate_order",axis:"structural_form",base:line,mutate:g=>{g.grainCandidates.reverse();return g},expect:"unchanged_or_incomparable"},
{id:"shuffle_raw_rows",axis:"structural_form",base:line,mutate:()=>build([["order","shipment","report date","quantity"],[2,"S-3","2026-01-03",20],[1,"S-2","2026-01-02",10],[1,"S-1","2026-01-01",10]]),expect:"unchanged_or_incomparable"},
{id:"add_unrelated_sibling_column",axis:"temporal_mode",base:event,mutate:()=>build([["report date","quantity","note"],["2026-01-01",1,"a"],["2026-01-02",2,"b"]]),expect:"unchanged_or_incomparable"},
{id:"add_compatible_temporal_axis",axis:"structural_form",base:entity,mutate:()=>build([["asset","report date"],["A-1","2026-01-01"],["A-2","2026-01-02"]]),expect:"not_increased"},
{id:"remove_one_axis_preserve_unrelated",axis:"structural_form",base:line,mutate:g=>{g.temporalBehaviors=[];g.grainCandidates=g.grainCandidates.filter(x=>x.rowUnitClass!=="event_record");return g},expect:"unchanged_or_incomparable"}
];
describe("Phase 4A2B counterfactual robustness",()=>{it("covers all 30 governed mutations with conservative monotonicity",()=>{expect(mutations).toHaveLength(30);const audit=mutations.map(m=>{const base=m.base(),before=resolve(base),mutated=m.mutate(clone(base)),after=resolve(mutated),beforeState=axisState(before,m.axis),afterState=axisState(after,m.axis),relation=certaintyRelation(beforeState,afterState),valid=m.expect==="not_increased"?relation!=="increased":relation!=="increased";expect(valid,m.id).toBe(true);expect(after.signature.measureSafety.safeToAggregate,m.id).toBe(false);return{mutation:m.id,axis:m.axis,originalAxisStates:{target:beforeState},mutatedAxisStates:{target:afterState},expectedMonotonicRelation:m.expect,actualRelation:relation,invariantResult:valid?"passed":"failed",policyRuleIds:[...new Set([...before.signature.structuralForm.governingRuleIds,...before.signature.identityBasis.governingRuleIds,...before.signature.parentBasis.governingRuleIds,...before.signature.temporalMode.governingRuleIds,...before.signature.aggregationForm.governingRuleIds])],evidenceDependencyChanges:{before:validateGrainResolution(base,before).dependencyGraph.length,after:validateGrainResolution(mutated,after).dependencyGraph.length},deterministicReplayResult:JSON.stringify(after)===JSON.stringify(resolve(mutated))};});expect(audit.every(x=>x.deterministicReplayResult)).toBe(true);if(process.env.LIGHTBI_WRITE_PHASE4A2B_AUDIT==="1")fs.writeFileSync(path.join(ROOT,"docs/architecture/phase-4a2b-counterfactual-audit.json"),`${JSON.stringify({schemaVersion:"lightbi.phase-4a2b-counterfactual-audit.v1",date:"2026-07-12",mutations:audit,summary:{total:audit.length,passed:audit.filter(x=>x.invariantResult==="passed").length,failed:audit.filter(x=>x.invariantResult==="failed").length}},null,2)}\n`);});});
