import { deterministicPolicySha256 } from "./contextual-evidence-policy";
import { LEGACY_CANONICAL_COMPARISON_POLICY_VERSION, type ComparisonMappingV1, type ComparisonPolicyV1 } from "./legacy-canonical-comparison-contracts";

export const COMPARISON_MAPPINGS: ComparisonMappingV1[] = [
  { mappingId:"MAP-NUMERIC-SUM-SAFETY",legacyModuleId:"numeric_health",legacyField:"isSafeForSum",canonicalCapabilities:["numeric_aggregation_ready"],validScopes:["source"],comparisonType:"partially_comparable",prerequisites:["legacy_boolean_present","guarded_sum_bridge_callpath"],authorityMeaning:"physical parse support drives automatic SUM default and generated SQL when no explicit aggregation exists",safetyMeaning:"physical operator support is not business additivity; conflict is authority-relevant only through the proven automatic path",allowedDivergences:["agreement_same_restriction","canonical_more_conservative","legacy_more_conservative","safety_conflict","numeric_score_not_comparable"],prohibitedInterpretations:["physical_summability_equals_semantic_additivity","score_to_readiness","automatic_winner"],rationale:"Legacy proves mechanical numeric parse support and uses it for automatic SUM selection; canonical blocks business-safe aggregation until measure and grain semantics are governed. The concepts are partial, while the production authority path creates a real safety conflict.",version:1 },
  { mappingId:"MAP-DATASET-HEALTH",legacyModuleId:"dataset_health",legacyField:"overall",canonicalCapabilities:["physical_profile_ready","structural_quality_assessment_ready"],validScopes:["source"],comparisonType:"partially_comparable",prerequisites:["legacy_score_present"],authorityMeaning:"display information",safetyMeaning:"none",allowedDivergences:["numeric_score_not_comparable","legacy_overstates_readiness","inconclusive"],prohibitedInterpretations:["numeric_threshold_to_state"],rationale:"Global physical score is not a canonical capability state.",version:1 },
  { mappingId:"MAP-DECISION-READINESS",legacyModuleId:"decision_readiness",legacyField:"score",canonicalCapabilities:["generic_analysis_ready","semantic_labeling_ready","grain_interpretation_ready"],validScopes:["source","bundle"],comparisonType:"structurally_incomparable",prerequisites:["legacy_score_present"],authorityMeaning:"user-facing guidance",safetyMeaning:"must_not_override_blockers",allowedDivergences:["numeric_score_not_comparable","legacy_overstates_readiness","inconclusive"],prohibitedInterpretations:["global_score_equivalence"],rationale:"One legacy score spans several independent canonical dimensions.",version:1 },
  { mappingId:"MAP-PLAN-STATUS",legacyModuleId:"virtual_dataset_planner",legacyField:"status",canonicalCapabilities:["join_planning_ready","append_planning_ready","join_execution_ready","append_execution_ready"],validScopes:["source_pair","bundle"],comparisonType:"authority_only_comparable",prerequisites:["legacy_status_present"],authorityMeaning:"planning",safetyMeaning:"operation restrictions",allowedDivergences:["agreement_same_restriction","authority_conflict","safety_conflict","scope_semantics_mismatch"],prohibitedInterpretations:["planning_equals_execution"],rationale:"Planner status can conflict with canonical operation restrictions.",version:1 },
  { mappingId:"MAP-DOMAIN-METRIC",legacyModuleId:"domain_metric",legacyField:"available",canonicalCapabilities:["domain_activation_ready","domain_metric_planning_ready"],validScopes:["source","bundle"],comparisonType:"directly_comparable",prerequisites:["legacy_boolean_present"],authorityMeaning:"domain output",safetyMeaning:"domain support required",allowedDivergences:["agreement_same_availability","safety_conflict","canonical_more_conservative"],prohibitedInterpretations:["semantic_coverage_activates_domain"],rationale:"Domain metric availability requires governed support.",version:1 }
];
export const LEGACY_CANONICAL_COMPARISON_POLICY: ComparisonPolicyV1 = {
  schemaVersion: LEGACY_CANONICAL_COMPARISON_POLICY_VERSION,
  mappings: COMPARISON_MAPPINGS,
  severityRules:[{ruleId:"CMP-SAFETY",severity:"critical"},{ruleId:"CMP-HIGH-SCORE-CONDITIONAL",severity:"material"},{ruleId:"CMP-SCALAR-INCOMPARABLE",severity:"caution"},{ruleId:"CMP-NO-EQUIVALENT",severity:"informational"}],
  forbiddenInterpretations:["global_equivalence_score","numeric_score_to_capability_state","automatic_migration_winner","authority_inference_from_name","validation_tuning"]
};
export const comparisonPolicyHash=(value:unknown=LEGACY_CANONICAL_COMPARISON_POLICY)=>deterministicPolicySha256(value);
