import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";
import { SEMANTIC_SIGNAL_REGISTRY_V1 } from "../semantic-registry";
import { aggregateContextualEvidence } from "./contextual-evidence-aggregator";
import type { CandidateAbsenceDebtV1 } from "./contextual-evidence-contracts";
import { profilePhysicalSource } from "./profiler";
import { generateSemanticCandidateArtifact } from "./semantic-candidate-engine";
import { resolveSemanticShadow } from "./semantic-resolver";
import type { SemanticResolutionState } from "./semantic-resolution-contracts";

const ROOT=path.resolve(__dirname,"../../../../..");
const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,"sample-corpus/versions/1.4.0/manifest.json"),"utf8")) as {groups:Record<string,{tuningAllowed:boolean}>,groundTruthFiles:Array<{path:string}>};
type Sample={id:string;group:"golden"|"holdout"|"adversarial"|"multi_file";provenance:{tuningUse:"allowed"|"forbidden"};sources:Array<{path:string;sheet:string;sha256:string}>;recognition:{requiredMappings:Array<{physicalColumn:string;canonicalSignal:string}>;expectedAmbiguousMappings:Array<{physicalColumn:string;candidateSignals:string[]}>}};
const documents=manifest.groundTruthFiles.map((e)=>JSON.parse(fs.readFileSync(path.join(ROOT,e.path),"utf8")) as {samples:Sample[];aliasCollisionCases?:Array<{normalizedAlias:string;candidateSignals:string[]}>});
const samples=documents.flatMap((d)=>d.samples);const cache=new Map<string,ReturnType<typeof sourceArtifacts>>();
function sourceArtifacts(source:Sample["sources"][number]){const bytes=fs.readFileSync(path.join(ROOT,source.path));expect(crypto.createHash("sha256").update(bytes).digest("hex")).toBe(source.sha256);const workbook=XLSX.read(bytes,{raw:true}),sheet=workbook.Sheets[source.sheet]??workbook.Sheets[workbook.SheetNames[0]];if(!sheet)throw new Error(`missing sheet ${source.path}#${source.sheet}`);const physical=profilePhysicalSource({schemaVersion:"lightbi.physical-source-input.v1",source:{sourceId:`${source.path}#${source.sheet}`,kind:"local_file",label:path.basename(source.path),hash:{algorithm:"sha256",value:source.sha256}},rawRows:XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:"",blankrows:true})});const candidate=generateSemanticCandidateArtifact(physical);return {physical,candidate};}
function artifacts(source:Sample["sources"][number]){const key=`${source.path}#${source.sheet}`;if(!cache.has(key))cache.set(key,sourceArtifacts(source));return cache.get(key)!;}
function debts(sample:Sample,all:ReturnType<typeof artifacts>[]):CandidateAbsenceDebtV1[]{const ids=(column:string)=>new Set(all.flatMap(({candidate})=>candidate.observations.filter((o)=>o.physicalColumn===column).flatMap((o)=>o.candidateSet.candidates.map((c)=>c.candidateId))));const result:CandidateAbsenceDebtV1[]=[];for(const m of sample.recognition.requiredMappings)if(!ids(m.physicalColumn).has(m.canonicalSignal))result.push({physicalColumn:`${sample.id}:${m.physicalColumn}`,candidateId:m.canonicalSignal,reasonCode:"required_candidate_absent"});for(const m of sample.recognition.expectedAmbiguousMappings)for(const id of m.candidateSignals)if(!ids(m.physicalColumn).has(id))result.push({physicalColumn:`${sample.id}:${m.physicalColumn}`,candidateId:id,reasonCode:"contextual_candidate_absent"});return result;}
describe.sequential("Phase 3B2A shadow resolution governance corpus",()=>{
  it("keeps non-golden groups validation-only and preserves all governed absence debts",()=>{const debt:CandidateAbsenceDebtV1[]=[];for(const sample of samples){expect(sample.provenance.tuningUse).toBe(manifest.groups[sample.group].tuningAllowed?"allowed":"forbidden");if(sample.group!=="golden")expect(sample.provenance.tuningUse).toBe("forbidden");const all=sample.sources.map(artifacts);debt.push(...debts(sample,all));}expect(debt.filter((d)=>d.reasonCode==="required_candidate_absent")).toHaveLength(2);expect(debt.filter((d)=>d.reasonCode==="contextual_candidate_absent")).toHaveLength(10);},120_000);
  it("evaluates all 30 cases conservatively and reports group-separated diagnostics",()=>{const stateByGroup:Record<string,Record<SemanticResolutionState,number>>={},dispositions:Record<string,number>={},selectedByLexicalClass:Record<string,number>={};let preserved=0,traces=0,broad=0,correlated=0,contextSelected=0,debtAffected=0,preventedConflict=0,preventedStructural=0,dominance=0;const seen=new Set<string>();
    for(const sample of samples){const all=sample.sources.map(artifacts),sampleDebt=debts(sample,all);stateByGroup[sample.group]??={confirmed:0,probable:0,ambiguous:0,unknown:0,technical:0,unsupported_input:0};for(const {physical,candidate} of all){const contextual=aggregateContextualEvidence(physical,candidate,sampleDebt),resolution=resolveSemanticShadow(physical,candidate,contextual);expect(resolution.productionWiring.executed).toBe(false);expect(resolution.coverage.resolvedColumnCount).toBe(resolution.coverage.physicalColumnCount);preserved+=resolution.candidatePreservationProof.inputCandidateCount;traces+=resolution.candidatePreservationProof.outputCandidateTraceCount;
      for(const column of resolution.columns){seen.add(column.physicalColumn);stateByGroup[sample.group][column.finalState]++;if(column.candidateTraces.length>=5)broad++;if(column.debt.length)debtAffected++;if(column.candidateTraces.some((t)=>t.materialConflictCodes.length))preventedConflict++;if(column.limitations.some((l)=>l.severity==="material"))preventedStructural++;if(column.candidateTraces.some((t)=>t.independence.correlatedEvidence.length))correlated++;if(column.candidateTraces.some((t)=>t.dominance.dominatedBy))dominance++;column.candidateTraces.forEach((t)=>dispositions[t.disposition]=(dispositions[t.disposition]??0)+1);const selected=column.candidateTraces.find((t)=>t.disposition==="selected");if(selected){selectedByLexicalClass[selected.lexicalClass]=(selectedByLexicalClass[selected.lexicalClass]??0)+1;}if(selected?.independence.independentContextFamilies.length)contextSelected++;
        if(column.physicalColumn==="y")expect(["unknown","ambiguous"]).toContain(column.finalState);
        if(column.physicalColumn==="Event")expect(column.selectedCandidateId??"").not.toMatch(/error_event|audit_action/);
        if(column.physicalColumn==="Status")expect(column.finalState).not.toBe("confirmed");
        if(column.physicalColumn==="UnitCost")expect(["unit","uom"]).not.toContain(column.selectedCandidateId);
      }} }
    expect(samples).toHaveLength(30);expect(preserved).toBe(traces);expect(broad).toBe(15);expect(Object.keys(stateByGroup).sort()).toEqual(["adversarial","golden","holdout","multi_file"]);expect({dispositions,selectedByLexicalClass,correlated,contextSelected,debtAffected,preventedConflict,preventedStructural,dominance}).toBeDefined();const mandatory=JSON.parse(fs.readFileSync(path.join(ROOT,"sample-corpus/shadow-resolution-expectations.v1.json"),"utf8")).mandatoryPhysicalColumns as string[];mandatory.forEach((column)=>expect(seen,column).toContain(column));
  },120_000);
  it("keeps all 84 header-only collisions ambiguous or unknown without mutual-context bootstrap",()=>{const cases=documents.flatMap((d)=>d.aliasCollisionCases??[]);expect(cases).toHaveLength(84);for(const collision of cases){const physical=profilePhysicalSource({schemaVersion:"lightbi.physical-source-input.v1",source:{sourceId:`collision:${collision.normalizedAlias}`,kind:"unknown",label:"collision"},rawRows:[[collision.normalizedAlias]]});const candidate=generateSemanticCandidateArtifact(physical,{registry:SEMANTIC_SIGNAL_REGISTRY_V1}),contextual=aggregateContextualEvidence(physical,candidate),result=resolveSemanticShadow(physical,candidate,contextual).columns[0];expect(["ambiguous","unknown"],collision.normalizedAlias).toContain(result.finalState);expect(result.finalState,collision.normalizedAlias).not.toBe("confirmed");collision.candidateSignals.forEach((id)=>expect(result.candidateTraces.map((t)=>t.candidateId)).toContain(id));}},120_000);
});
