import { describe, expect, it } from "vitest";
import { aggregateContextualEvidence } from "./contextual-evidence-aggregator";
import type { ContextualEvidenceArtifactV1 } from "./contextual-evidence-contracts";
import { profilePhysicalSource } from "./profiler";
import type { CandidateArtifactV1 } from "./semantic-candidate-contracts";
import { generateSemanticCandidateArtifact } from "./semantic-candidate-engine";
import { canonicalResolutionJson, SEMANTIC_RESOLUTION_POLICY, semanticResolutionPolicyHash } from "./semantic-resolution-policy";
import type { ColumnSemanticResolutionV1, SemanticResolutionState } from "./semantic-resolution-contracts";
import { resolveSemanticShadow } from "./semantic-resolver";

const certainty=(state:SemanticResolutionState)=>state==="confirmed"?2:state==="probable"?1:state==="ambiguous"||state==="unknown"?0:null;
function expectNoIncrease(before:ColumnSemanticResolutionV1,after:ColumnSemanticResolutionV1){const a=certainty(before.finalState),b=certainty(after.finalState);if(a!=null&&b!=null)expect(b).toBeLessThanOrEqual(a);}
function build(rows:unknown[][]){const physical=profilePhysicalSource({schemaVersion:"lightbi.physical-source-input.v1",source:{sourceId:"counterfactual",kind:"unknown",label:"counterfactual",hash:{algorithm:"sha256",value:"stable"}},rawRows:rows});const candidate=generateSemanticCandidateArtifact(physical),contextual=aggregateContextualEvidence(physical,candidate);return {physical,candidate,contextual,resolution:resolveSemanticShadow(physical,candidate,contextual)};}
function column(result:ReturnType<typeof build>["resolution"],name:string){return result.columns.find((item)=>item.physicalColumn===name)!;}
function resolve(base:ReturnType<typeof build>,candidate:CandidateArtifactV1=base.candidate,contextual?:ContextualEvidenceArtifactV1){const context=contextual??aggregateContextualEvidence(base.physical,candidate);return resolveSemanticShadow(base.physical,candidate,context);}

describe("Phase 3B2B counterfactual robustness and monotonicity",()=>{
  it("removing cardinality, exact lexical, representative values, or context cannot increase certainty",()=>{const base=build([["OrderID","Order Name"],["ORD-1","One"],["ORD-2","Two"]]),original=column(base.resolution,"OrderID");
    const noCard=structuredClone(base.candidate);noCard.observations[0].candidateSet.candidates.forEach((c)=>c.evidence=c.evidence.filter((e)=>e.type!=="identifier_shape"));expectNoIncrease(original,column(resolve(base,noCard),"OrderID"));
    const weak=structuredClone(base.candidate);weak.observations[0].candidateSet.candidates.forEach((c)=>c.evidence.forEach((e)=>{if(["canonical_header_exact","header_alias_exact","alias_exact"].includes(e.type))e.type="alias_token_containment";}));expectNoIncrease(original,column(resolve(base,weak),"OrderID"));
    const noValues=structuredClone(base.candidate);noValues.observations[0].candidateSet.candidates.forEach((c)=>c.evidence=c.evidence.filter((e)=>e.source!=="representative_evidence"));expectNoIncrease(original,column(resolve(base,noValues),"OrderID"));
    const noContext=structuredClone(base.contextual);noContext.observations.forEach((o)=>o.candidateProfiles.forEach((p)=>{p.contextRelations=[];const family=p.familyAssessments.find((f)=>f.family==="sibling_context");if(family){family.assessment="unavailable";family.evidenceReferences=[];family.independentContributionCount=0;}}));expectNoIncrease(original,column(resolve(base,base.candidate,noContext),"OrderID"));
  });
  it("opaque headers, viable competitors, collisions, and material absence never increase certainty",()=>{const base=build([["OrderID"],["ORD-1"],["ORD-2"]]),original=base.resolution.columns[0];const opaque=build([["opaque field"],["ORD-1"],["ORD-2"]]).resolution.columns[0];expectNoIncrease(original,opaque);
    const collision=build([["Status"],["Open"],["Closed"]]).resolution.columns[0];expect(["ambiguous","unknown"]).toContain(collision.finalState);
    const competitorCandidate=structuredClone(base.candidate),competitorContext=structuredClone(base.contextual),sourceCandidate=competitorCandidate.observations[0].candidateSet.candidates[0],sourceProfile=competitorContext.observations[0].candidateProfiles[0];competitorCandidate.observations[0].candidateSet.candidates.push({...structuredClone(sourceCandidate),candidateId:"synthetic_competitor"});competitorCandidate.observations[0].candidateSet.hasAliasCollision=true;competitorContext.observations[0].candidateProfiles.push({...structuredClone(sourceProfile),candidateId:"synthetic_competitor"});expectNoIncrease(original,column(resolve(base,competitorCandidate,competitorContext),"OrderID"));
    const debt=aggregateContextualEvidence(base.physical,base.candidate,[{physicalColumn:"OrderID",candidateId:"material_alternative",reasonCode:"synthetic_material_gap"}]);expectNoIncrease(original,column(resolve(base,base.candidate,debt),"OrderID"));
    const unrelatedDebt=aggregateContextualEvidence(base.physical,base.candidate,[{physicalColumn:"OtherColumn",candidateId:"unrelated_alternative",reasonCode:"synthetic_unrelated_gap"}]);const unrelatedResult=column(resolve(base,base.candidate,unrelatedDebt),"OrderID");expect(unrelatedResult.finalState).toBe(original.finalState);expect(unrelatedResult.selectedCandidateId).toBe(original.selectedCandidateId);
  });
  it("physical conflicts, parse/mixed uncertainty, and representative-only provenance never increase certainty",()=>{const base=build([["OrderID"],["ORD-1"],["ORD-2"]]),original=base.resolution.columns[0];const conflict=structuredClone(base.candidate);conflict.observations[0].candidateSet.candidates.forEach((c)=>c.evidence.forEach((e)=>{if(e.type==="physical_type_compatible"){e.type="physical_type_conflict";e.direction="conflict";e.explanationCode="synthetic_physical_conflict";}}));expectNoIncrease(original,column(resolve(base,conflict),"OrderID"));
    const mixed=structuredClone(base.physical);mixed.sourceProfile.columns[0].issues.push({code:"mixed_type",severity:"warning",physicalColumn:"OrderID",sourceRowIndices:[1],evidence:["synthetic mixed type"]});const mixedContext=aggregateContextualEvidence(mixed,base.candidate);expectNoIncrease(original,resolveSemanticShadow(mixed,base.candidate,mixedContext).columns[0]);
    const representative=structuredClone(base.candidate);representative.observations[0].candidateSet.candidates.forEach((c)=>c.evidence.forEach((e)=>{if(e.source==="source_profile")e.source="representative_evidence";}));expectNoIncrease(original,column(resolve(base,representative),"OrderID"));
  });
  it("duplicates and evidence shuffles are certainty-neutral and byte-stable",()=>{const base=build([["Quantity","Unit"],[10,"kg"],[20,"kg"]]),baseline=base.resolution;const duplicate=structuredClone(base.candidate);duplicate.observations.forEach((o)=>o.candidateSet.candidates.forEach((c)=>{c.evidence.reverse();if(c.evidence[0])c.evidence.push({...c.evidence[0],evidenceId:`${c.evidence[0].evidenceId}:duplicate`});}));expect(canonicalResolutionJson(resolve(base,duplicate))).toBe(canonicalResolutionJson(baseline));
    const relationDuplicate=structuredClone(base.contextual);relationDuplicate.observations.forEach((o)=>o.candidateProfiles.forEach((p)=>{if(p.contextRelations[0])p.contextRelations.push({...p.contextRelations[0],relationEvidenceId:`${p.contextRelations[0].relationEvidenceId}:duplicate`});}));const mutated=resolve(base,base.candidate,relationDuplicate);mutated.columns.flatMap((c)=>c.candidateTraces).forEach((trace)=>expect(new Set(trace.independence.independentContextFamilies).size).toBeLessThanOrEqual(1));baseline.columns.forEach((c)=>expectNoIncrease(c,column(mutated,c.physicalColumn)));
  });
  it("unrelated sibling order/candidates and relation endpoint removal cannot increase certainty",()=>{const base=build([["OrderID","Order Name","Noise"],["ORD-1","One","x"],["ORD-2","Two","y"]]),target=column(base.resolution,"OrderID");const reordered=build([["Noise","Order Name","OrderID"],["x","One","ORD-1"],["y","Two","ORD-2"]]);expect(column(reordered.resolution,"OrderID").finalState).toBe(target.finalState);expect(column(reordered.resolution,"OrderID").selectedCandidateId).toBe(target.selectedCandidateId);
    const unrelated=build([["OrderID","Order Name","Noise","Campaign"],["ORD-1","One","x","A"],["ORD-2","Two","y","B"]]);expect(column(unrelated.resolution,"OrderID").finalState).toBe(target.finalState);expect(column(unrelated.resolution,"OrderID").selectedCandidateId).toBe(target.selectedCandidateId);
    const removed=structuredClone(base.contextual);removed.observations.find((o)=>o.physicalColumn==="OrderID")?.candidateProfiles.forEach((p)=>p.contextRelations=[]);expectNoIncrease(target,column(resolve(base,base.candidate,removed),"OrderID"));
  });
  it("mutual weak context, sparse data, technical and unsupported input remain conservative",()=>{const weak=build([["Quantity","Unit"],["x","y"]]);const context=structuredClone(weak.contextual);context.observations.forEach((o)=>o.candidateProfiles.forEach((p)=>{p.supportingEvidence=p.supportingEvidence.filter((e)=>e.source==="semantic_registry");p.familyAssessments.forEach((f)=>{if(f.family!=="lexical_identity"&&f.family!=="sibling_context")f.assessment="unavailable";});}));const weakResult=resolve(weak,weak.candidate,context);weakResult.columns.forEach((c)=>expect(["unknown","ambiguous"]).toContain(c.finalState));
    const dense=build([["OrderID"],["ORD-1"],["ORD-2"]]),sparse=build([["OrderID"],["ORD-1"],[""],[""],["ORD-2"],[""]]);expectNoIncrease(dense.resolution.columns[0],sparse.resolution.columns[0]);
    expect(build([["__PowerAppsId__"],["a886d124-31d9-4a9a-a3e2-000000000001"]]).resolution.columns[0].finalState).toBe("technical");expect(build([["__EMPTY"],["value"]]).resolution.columns[0].finalState).toBe("unsupported_input");
  });
  it("policy formatting/key order is hash-stable while semantic mutation changes identity",()=>{expect(semanticResolutionPolicyHash({a:1,b:{c:2}})).toBe(semanticResolutionPolicyHash({b:{c:2},a:1}));expect(semanticResolutionPolicyHash({...SEMANTIC_RESOLUTION_POLICY,rules:[...SEMANTIC_RESOLUTION_POLICY.rules,{ruleId:"mutation",description:"mutation",outcome:"governance"}]})).not.toBe(semanticResolutionPolicyHash());});
});
