import assert from 'node:assert/strict'; import test from 'node:test';
import { canonicalText, sha256Hex } from './canonical.js'; import { entitlementPayloadV1Schema, installationCertificatePayloadV1Schema, issuerKeyRecordV1Schema, proPackagePayloadV1Schema, releasePayloadV1Schema, signedEntitlementEnvelopeSchema } from './schemas.js';
const entitlement={schema:1 as const,kid:'ent-2026-01',entitlement_id:'ent_org_demo',subject:{type:'organization' as const,id:'org_demo'},tier:'business' as const,capabilities:['pro_runtime','dashboard','advanced_scale'],issued_at:'2026-08-29T05:17:00Z',valid_until:'2027-08-29T05:17:00Z',entitlement_version:1,source:'internal' as const,seat_limit:20};
test('strict UTC timestamps reject offsets, milliseconds, invalid dates and reversed validity',()=>{assert.equal(entitlementPayloadV1Schema.safeParse(entitlement).success,true);assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,issued_at:'2026-08-29T12:17:00+07:00'}).success,false);assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,issued_at:'2026-08-29T05:17:00.000Z'}).success,false);assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,issued_at:'2026-02-30T05:17:00Z'}).success,false);assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,valid_until:'2025-08-29T05:17:00Z'}).success,false);});
test('duplicate capabilities are invalid before canonicalization',()=>{assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,capabilities:['dashboard','dashboard']}).success,false);});
test('organization business seat semantics fail closed',()=>{assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,seat_limit:25}).success,true);assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,seat_limit:7}).success,false);assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,subject:{type:'account',id:'acct_demo'},tier:'pro',seat_limit:5}).success,false);assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,seat_limit:undefined}).success,false);});
test('unknown fields, purpose, schema and mismatched kid are rejected',()=>{assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,surprise:true}).success,false);assert.equal(issuerKeyRecordV1Schema.safeParse({kid:'x-1',purpose:'anything',algorithm:'Ed25519',public_key:'abc',status:'active',not_before:entitlement.issued_at,not_after:entitlement.valid_until}).success,false);assert.equal(entitlementPayloadV1Schema.safeParse({...entitlement,schema:2}).success,false);assert.equal(signedEntitlementEnvelopeSchema.safeParse({schema:1,kid:'ent-other',payload:entitlement,signature:'abc'}).success,false);});
test('canonical bytes are semantic-order stable and semantic changes diverge',()=>{const parsed=entitlementPayloadV1Schema.parse(entitlement);const reordered={...parsed,capabilities:['advanced_scale','dashboard','pro_runtime']};const a=canonicalText(parsed),b=canonicalText(reordered);assert.equal(a,b);assert.equal(sha256Hex(new TextEncoder().encode(a)),sha256Hex(new TextEncoder().encode(b)));assert.notEqual(a,canonicalText({...parsed,seat_limit:25}));assert.notEqual(a,canonicalText({...parsed,subject:{type:'organization',id:'org_other'}}));assert.throws(()=>canonicalText({...parsed,seat_limit:20.5}));assert.throws(()=>canonicalText({...parsed,unexpected:undefined}),/canonical_undefined_is_invalid/);});
test('release, installation certificate and Pro package v1 contracts are strict',()=>{const common={schema:1 as const,kid:'rel-2026-01',product_id:'digital.thaiduy.lightbi',version:'0.9.2-beta.7',platform:'windows' as const,architecture:'x86_64'};assert.equal(releasePayloadV1Schema.safeParse({...common,release_id:'release_demo',channel:'beta',artifact_name:'LightBI.exe',artifact_sha256:'a'.repeat(64),artifact_size:1,created_at:entitlement.issued_at}).success,true);assert.equal(installationCertificatePayloadV1Schema.safeParse({schema:1,kid:'att-2026-01',product_id:common.product_id,installation_id:'install_demo',device_public_key:'abc',release_id:'release_demo',platform:'windows',architecture:'x86_64',issued_at:entitlement.issued_at,expires_at:entitlement.valid_until,certificate_id:'cert_demo'}).success,true);assert.equal(proPackagePayloadV1Schema.safeParse({...common,kid:'pro-2026-01',package_id:'pkg_demo',core_min:'0.9.2-beta.7',core_max:'0.9.9-beta.9',sha256:'b'.repeat(64),size:1,issued_at:entitlement.issued_at}).success,true);assert.equal(proPackagePayloadV1Schema.safeParse({...common,kid:'pro-2026-01',package_id:'pkg_demo',core_min:'x',core_max:'y',sha256:'b'.repeat(64),size:1.5,issued_at:entitlement.issued_at}).success,false);});
