// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayloadVersion } from "./PayloadVersion";

export type ChartPayload = { id: string, chart_type: string, mappings: { [key: string]: string }, theme_metadata: any, payload_version: PayloadVersion, };