// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayloadVersion } from "./PayloadVersion";
import type { WidgetPayload } from "./WidgetPayload";

export type DashboardPayload = { id: string, title: string, perspective_id: string, layout_metadata: any, widgets: Array<WidgetPayload>, payload_version: PayloadVersion, };