// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayloadVersion } from "./PayloadVersion";

export type ExportPayload = { id: string, artifact_type: string, download_url: string, payload_version: PayloadVersion, };