// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayloadVersion } from "./PayloadVersion";

export type InsightPayload = { id: string, insight_type: string, observation_text: string, confidence: number, payload_version: PayloadVersion, };